var graph_anonymous = {
	"nodes": [
		{"id": "covid", "group": 1},
		{"id": "probably", "group": 1},
		{"id": "something", "group": 1},
		{"id": "made", "group": 1},
		{"id": "theyre", "group": 1},
		{"id": "covid19", "group": 1},
		{"id": "also", "group": 1},
		{"id": "pneumonia", "group": 1},
		{"id": "school", "group": 1},
		{"id": "pay", "group": 1},
		{"id": "started", "group": 1},
		{"id": "different", "group": 1},
		{"id": "nothing", "group": 1},
		{"id": "yes", "group": 1},
		{"id": "without", "group": 1},
		{"id": "seems", "group": 1},
		{"id": "look", "group": 1},
		{"id": "etc", "group": 1},
		{"id": "hospital", "group": 1},
		{"id": "someone", "group": 1},
		{"id": "eat", "group": 1},
		{"id": "positive", "group": 2},
		{"id": "use", "group": 2},
		{"id": "coming", "group": 2},
		{"id": "thought", "group": 2},
		{"id": "place", "group": 2},
		{"id": "kind", "group": 2},
		{"id": "isnt", "group": 2},
		{"id": "thinking", "group": 2},
		{"id": "maybe", "group": 2},
		{"id": "anything", "group": 2},
		{"id": "public", "group": 2},
		{"id": "situation", "group": 2},
		{"id": "stuff", "group": 2},
		{"id": "said", "group": 2},
		{"id": "great", "group": 2},
		{"id": "state", "group": 2},
		{"id": "medical", "group": 2},
		{"id": "coronavirus", "group": 3},
		{"id": "leave", "group": 3},
		{"id": "fea", "group": 3},
		{"id": "already", "group": 3},
		{"id": "parents", "group": 3},
		{"id": "local", "group": 3},
		{"id": "panic", "group": 3},
		{"id": "job", "group": 3},
		{"id": "would", "group": 3},
		{"id": "spread", "group": 3},
		{"id": "come", "group": 3},
		{"id": "smell", "group": 4},
		{"id": "instead", "group": 4},
		{"id": "fa", "group": 4},
		{"id": "extra", "group": 4},
		{"id": "spreading", "group": 4},
		{"id": "seen", "group": 4},
		{"id": "eve", "group": 4},
		{"id": "hours", "group": 4},
		{"id": "put", "group": 4},
		{"id": "half", "group": 4},
		{"id": "clean", "group": 4},
		{"id": "food", "group": 4},
		{"id": "plus", "group": 4},
		{"id": "aware", "group": 4},
		{"id": "supplies", "group": 4},
		{"id": "case", "group": 4},
		{"id": "reddit", "group": 4},
		{"id": "anxiety", "group": 4},
		{"id": "taste", "group": 5},
		{"id": "brain", "group": 5},
		{"id": "wait", "group": 5},
		{"id": "shit", "group": 5},
		{"id": "self", "group": 5},
		{"id": "saying", "group": 5},
		{"id": "concern", "group": 5},
		{"id": "country", "group": 5},
		{"id": "wasnt", "group": 5},
		{"id": "mom", "group": 5},
		{"id": "large", "group": 5},
		{"id": "area", "group": 5},
		{"id": "months", "group": 5},
		{"id": "travel", "group": 5},
		{"id": "arent", "group": 5},
		{"id": "believe", "group": 5},
		{"id": "symptoms", "group": 6},
		{"id": "flu", "group": 6},
		{"id": "feve", "group": 6},
		{"id": "cold", "group": 6},
		{"id": "cough", "group": 6},
		{"id": "bad", "group": 6},
		{"id": "got", "group": 6},
		{"id": "china", "group": 6},
		{"id": "away", "group": 6},
		{"id": "contact", "group": 6},
		{"id": "breath", "group": 6},
		{"id": "month", "group": 6},
		{"id": "went", "group": 6},
		{"id": "tested", "group": 6},
		{"id": "week", "group": 6},
		{"id": "negative", "group": 7},
		{"id": "work", "group": 7},
		{"id": "still", "group": 7},
		{"id": "anothe", "group": 7},
		{"id": "back", "group": 7},
		{"id": "left", "group": 7},
		{"id": "neve", "group": 7},
		{"id": "late", "group": 7},
		{"id": "night", "group": 7},
		{"id": "felt", "group": 7},
		{"id": "theres", "group": 7},
		{"id": "next", "group": 7},
		{"id": "call", "group": 7},
		{"id": "test", "group": 7},
		{"id": "cannot", "group": 7},
		{"id": "doctors", "group": 7}
	],
	"links": [
		{"source": "covid", "target": "probably", "value": 4},
		{"source": "covid", "target": "something", "value": 4},
		{"source": "covid", "target": "made", "value": 4},
		{"source": "covid", "target": "theyre", "value": 4},
		{"source": "covid", "target": "covid19", "value": 4},
		{"source": "covid", "target": "also", "value": 4},
		{"source": "covid", "target": "pneumonia", "value": 4},
		{"source": "covid", "target": "school", "value": 4},
		{"source": "covid", "target": "pay", "value": 4},
		{"source": "covid", "target": "started", "value": 4},
		{"source": "covid", "target": "different", "value": 4},
		{"source": "covid", "target": "nothing", "value": 4},
		{"source": "covid", "target": "yes", "value": 4},
		{"source": "covid", "target": "without", "value": 4},
		{"source": "covid", "target": "seems", "value": 4},
		{"source": "covid", "target": "look", "value": 4},
		{"source": "covid", "target": "etc", "value": 4},
		{"source": "covid", "target": "hospital", "value": 4},
		{"source": "covid", "target": "someone", "value": 4},
		{"source": "covid", "target": "eat", "value": 4},
		{"source": "positive", "target": "covid19", "value": 4},
		{"source": "positive", "target": "use", "value": 4},
		{"source": "positive", "target": "coming", "value": 4},
		{"source": "positive", "target": "thought", "value": 4},
		{"source": "positive", "target": "place", "value": 4},
		{"source": "positive", "target": "probably", "value": 4},
		{"source": "positive", "target": "kind", "value": 4},
		{"source": "positive", "target": "isnt", "value": 4},
		{"source": "positive", "target": "thinking", "value": 4},
		{"source": "positive", "target": "maybe", "value": 4},
		{"source": "positive", "target": "nothing", "value": 4},
		{"source": "positive", "target": "different", "value": 4},
		{"source": "positive", "target": "anything", "value": 4},
		{"source": "positive", "target": "public", "value": 4},
		{"source": "positive", "target": "situation", "value": 4},
		{"source": "positive", "target": "stuff", "value": 4},
		{"source": "positive", "target": "said", "value": 4},
		{"source": "positive", "target": "great", "value": 4},
		{"source": "positive", "target": "state", "value": 4},
		{"source": "positive", "target": "medical", "value": 4},
		{"source": "coronavirus", "target": "leave", "value": 4},
		{"source": "coronavirus", "target": "fea", "value": 4},
		{"source": "coronavirus", "target": "already", "value": 4},
		{"source": "coronavirus", "target": "coming", "value": 4},
		{"source": "coronavirus", "target": "parents", "value": 4},
		{"source": "coronavirus", "target": "said", "value": 4},
		{"source": "coronavirus", "target": "thought", "value": 4},
		{"source": "coronavirus", "target": "state", "value": 4},
		{"source": "coronavirus", "target": "local", "value": 4},
		{"source": "coronavirus", "target": "also", "value": 4},
		{"source": "coronavirus", "target": "panic", "value": 4},
		{"source": "coronavirus", "target": "job", "value": 4},
		{"source": "coronavirus", "target": "started", "value": 4},
		{"source": "coronavirus", "target": "would", "value": 4},
		{"source": "coronavirus", "target": "spread", "value": 4},
		{"source": "coronavirus", "target": "without", "value": 4},
		{"source": "coronavirus", "target": "nothing", "value": 4},
		{"source": "coronavirus", "target": "covid19", "value": 4},
		{"source": "coronavirus", "target": "made", "value": 4},
		{"source": "coronavirus", "target": "come", "value": 4},
		{"source": "smell", "target": "instead", "value": 4},
		{"source": "smell", "target": "fa", "value": 4},
		{"source": "smell", "target": "extra", "value": 4},
		{"source": "smell", "target": "spreading", "value": 4},
		{"source": "smell", "target": "seen", "value": 4},
		{"source": "smell", "target": "eve", "value": 4},
		{"source": "smell", "target": "hours", "value": 4},
		{"source": "smell", "target": "put", "value": 4},
		{"source": "smell", "target": "half", "value": 4},
		{"source": "smell", "target": "clean", "value": 4},
		{"source": "smell", "target": "food", "value": 4},
		{"source": "smell", "target": "plus", "value": 4},
		{"source": "smell", "target": "aware", "value": 4},
		{"source": "smell", "target": "supplies", "value": 4},
		{"source": "smell", "target": "different", "value": 4},
		{"source": "smell", "target": "coming", "value": 4},
		{"source": "smell", "target": "case", "value": 4},
		{"source": "smell", "target": "something", "value": 4},
		{"source": "smell", "target": "reddit", "value": 4},
		{"source": "smell", "target": "anxiety", "value": 4},
		{"source": "taste", "target": "brain", "value": 4},
		{"source": "taste", "target": "parents", "value": 4},
		{"source": "taste", "target": "wait", "value": 4},
		{"source": "taste", "target": "shit", "value": 4},
		{"source": "taste", "target": "self", "value": 4},
		{"source": "taste", "target": "saying", "value": 4},
		{"source": "taste", "target": "concern", "value": 4},
		{"source": "taste", "target": "country", "value": 4},
		{"source": "taste", "target": "wasnt", "value": 4},
		{"source": "taste", "target": "mom", "value": 4},
		{"source": "taste", "target": "large", "value": 4},
		{"source": "taste", "target": "area", "value": 4},
		{"source": "taste", "target": "seems", "value": 4},
		{"source": "taste", "target": "anxiety", "value": 4},
		{"source": "taste", "target": "months", "value": 4},
		{"source": "taste", "target": "travel", "value": 4},
		{"source": "taste", "target": "fa", "value": 4},
		{"source": "taste", "target": "seen", "value": 4},
		{"source": "taste", "target": "arent", "value": 4},
		{"source": "taste", "target": "believe", "value": 4},
		{"source": "symptoms", "target": "flu", "value": 4},
		{"source": "symptoms", "target": "feve", "value": 4},
		{"source": "symptoms", "target": "cold", "value": 4},
		{"source": "symptoms", "target": "cough", "value": 4},
		{"source": "symptoms", "target": "pneumonia", "value": 4},
		{"source": "symptoms", "target": "bad", "value": 4},
		{"source": "symptoms", "target": "got", "value": 4},
		{"source": "symptoms", "target": "started", "value": 4},
		{"source": "symptoms", "target": "china", "value": 4},
		{"source": "symptoms", "target": "away", "value": 4},
		{"source": "symptoms", "target": "hospital", "value": 4},
		{"source": "symptoms", "target": "contact", "value": 4},
		{"source": "symptoms", "target": "months", "value": 4},
		{"source": "symptoms", "target": "breath", "value": 4},
		{"source": "symptoms", "target": "month", "value": 4},
		{"source": "symptoms", "target": "went", "value": 4},
		{"source": "symptoms", "target": "tested", "value": 4},
		{"source": "symptoms", "target": "covid", "value": 4},
		{"source": "symptoms", "target": "week", "value": 4},
		{"source": "symptoms", "target": "public", "value": 4},
		{"source": "negative", "target": "covid19", "value": 4},
		{"source": "negative", "target": "work", "value": 4},
		{"source": "negative", "target": "still", "value": 4},
		{"source": "negative", "target": "anothe", "value": 4},
		{"source": "negative", "target": "back", "value": 4},
		{"source": "negative", "target": "left", "value": 4},
		{"source": "negative", "target": "fea", "value": 4},
		{"source": "negative", "target": "neve", "value": 4},
		{"source": "negative", "target": "late", "value": 4},
		{"source": "negative", "target": "thought", "value": 4},
		{"source": "negative", "target": "night", "value": 4},
		{"source": "negative", "target": "felt", "value": 4},
		{"source": "negative", "target": "theres", "value": 4},
		{"source": "negative", "target": "next", "value": 4},
		{"source": "negative", "target": "anything", "value": 4},
		{"source": "negative", "target": "call", "value": 4},
		{"source": "negative", "target": "test", "value": 4},
		{"source": "negative", "target": "job", "value": 4},
		{"source": "negative", "target": "cannot", "value": 4},
		{"source": "negative", "target": "doctors", "value": 4}
	]
}
