var graph_anonymous = {
	"nodes": [
		{"id": "covid", "group": 1},
		{"id": "see", "group": 1},
		{"id": "flu", "group": 1},
		{"id": "around", "group": 1},
		{"id": "news", "group": 1},
		{"id": "already", "group": 1},
		{"id": "could", "group": 1},
		{"id": "im", "group": 1},
		{"id": "way", "group": 1},
		{"id": "fo", "group": 1},
		{"id": "ou", "group": 1},
		{"id": "situation", "group": 1},
		{"id": "weeks", "group": 1},
		{"id": "ove", "group": 1},
		{"id": "take", "group": 1},
		{"id": "people", "group": 1},
		{"id": "time", "group": 1},
		{"id": "everyone", "group": 1},
		{"id": "things", "group": 1},
		{"id": "get", "group": 1},
		{"id": "virus", "group": 1},
		{"id": "positive", "group": 2},
		{"id": "thei", "group": 2},
		{"id": "help", "group": 2},
		{"id": "think", "group": 2},
		{"id": "family", "group": 2},
		{"id": "othe", "group": 2},
		{"id": "well", "group": 2},
		{"id": "risk", "group": 2},
		{"id": "hospital", "group": 2},
		{"id": "us", "group": 2},
		{"id": "also", "group": 2},
		{"id": "bad", "group": 2},
		{"id": "cases", "group": 2},
		{"id": "information", "group": 2},
		{"id": "ive", "group": 2},
		{"id": "coronavirus", "group": 3},
		{"id": "live", "group": 3},
		{"id": "find", "group": 3},
		{"id": "new", "group": 3},
		{"id": "anxiety", "group": 3},
		{"id": "may", "group": 3},
		{"id": "symptoms", "group": 3},
		{"id": "share", "group": 3},
		{"id": "go", "group": 3},
		{"id": "need", "group": 3},
		{"id": "since", "group": 3},
		{"id": "person", "group": 3},
		{"id": "smell", "group": 4},
		{"id": "orde", "group": 4},
		{"id": "worry", "group": 4},
		{"id": "cough", "group": 4},
		{"id": "know", "group": 4},
		{"id": "severe", "group": 4},
		{"id": "id", "group": 4},
		{"id": "shit", "group": 4},
		{"id": "anything", "group": 4},
		{"id": "fast", "group": 4},
		{"id": "play", "group": 4},
		{"id": "gave", "group": 4},
		{"id": "simila", "group": 4},
		{"id": "smoke", "group": 4},
		{"id": "cannot", "group": 4},
		{"id": "old", "group": 4},
		{"id": "corona", "group": 4},
		{"id": "groceries", "group": 4},
		{"id": "found", "group": 4},
		{"id": "taste", "group": 5},
		{"id": "stress", "group": 5},
		{"id": "top", "group": 5},
		{"id": "anothe", "group": 5},
		{"id": "late", "group": 5},
		{"id": "long", "group": 5},
		{"id": "pape", "group": 5},
		{"id": "last", "group": 5},
		{"id": "caught", "group": 5},
		{"id": "got", "group": 5},
		{"id": "talk", "group": 5},
		{"id": "else", "group": 5},
		{"id": "completely", "group": 5},
		{"id": "ago", "group": 5},
		{"id": "control", "group": 5},
		{"id": "hate", "group": 5},
		{"id": "end", "group": 5},
		{"id": "someone", "group": 6},
		{"id": "getting", "group": 6},
		{"id": "first", "group": 6},
		{"id": "even", "group": 6},
		{"id": "many", "group": 6},
		{"id": "probably", "group": 6},
		{"id": "come", "group": 6},
		{"id": "negative", "group": 7},
		{"id": "lives", "group": 7},
		{"id": "making", "group": 7},
		{"id": "taking", "group": 7},
		{"id": "good", "group": 7},
		{"id": "sleep", "group": 7},
		{"id": "trying", "group": 7},
		{"id": "put", "group": 7},
		{"id": "love", "group": 7},
		{"id": "two", "group": 7},
		{"id": "life", "group": 7},
		{"id": "home", "group": 7},
		{"id": "afte", "group": 7},
		{"id": "food", "group": 7},
		{"id": "one", "group": 7}
	],
	"links": [
		{"source": "covid", "target": "see", "value": 4},
		{"source": "covid", "target": "flu", "value": 4},
		{"source": "covid", "target": "around", "value": 4},
		{"source": "covid", "target": "news", "value": 4},
		{"source": "covid", "target": "already", "value": 4},
		{"source": "covid", "target": "could", "value": 4},
		{"source": "covid", "target": "im", "value": 4},
		{"source": "covid", "target": "way", "value": 4},
		{"source": "covid", "target": "fo", "value": 4},
		{"source": "covid", "target": "ou", "value": 4},
		{"source": "covid", "target": "situation", "value": 4},
		{"source": "covid", "target": "weeks", "value": 4},
		{"source": "covid", "target": "ove", "value": 4},
		{"source": "covid", "target": "take", "value": 4},
		{"source": "covid", "target": "people", "value": 4},
		{"source": "covid", "target": "time", "value": 4},
		{"source": "covid", "target": "everyone", "value": 4},
		{"source": "covid", "target": "things", "value": 4},
		{"source": "covid", "target": "get", "value": 4},
		{"source": "covid", "target": "virus", "value": 4},
		{"source": "positive", "target": "thei", "value": 4},
		{"source": "positive", "target": "help", "value": 4},
		{"source": "positive", "target": "virus", "value": 4},
		{"source": "positive", "target": "think", "value": 4},
		{"source": "positive", "target": "family", "value": 4},
		{"source": "positive", "target": "othe", "value": 4},
		{"source": "positive", "target": "well", "value": 4},
		{"source": "positive", "target": "way", "value": 4},
		{"source": "positive", "target": "people", "value": 4},
		{"source": "positive", "target": "time", "value": 4},
		{"source": "positive", "target": "risk", "value": 4},
		{"source": "positive", "target": "hospital", "value": 4},
		{"source": "positive", "target": "us", "value": 4},
		{"source": "positive", "target": "also", "value": 4},
		{"source": "positive", "target": "bad", "value": 4},
		{"source": "positive", "target": "cases", "value": 4},
		{"source": "positive", "target": "information", "value": 4},
		{"source": "positive", "target": "take", "value": 4},
		{"source": "positive", "target": "ive", "value": 4},
		{"source": "positive", "target": "ove", "value": 4},
		{"source": "coronavirus", "target": "news", "value": 4},
		{"source": "coronavirus", "target": "covid", "value": 4},
		{"source": "coronavirus", "target": "live", "value": 4},
		{"source": "coronavirus", "target": "find", "value": 4},
		{"source": "coronavirus", "target": "virus", "value": 4},
		{"source": "coronavirus", "target": "new", "value": 4},
		{"source": "coronavirus", "target": "anxiety", "value": 4},
		{"source": "coronavirus", "target": "may", "value": 4},
		{"source": "coronavirus", "target": "symptoms", "value": 4},
		{"source": "coronavirus", "target": "thei", "value": 4},
		{"source": "coronavirus", "target": "share", "value": 4},
		{"source": "coronavirus", "target": "go", "value": 4},
		{"source": "coronavirus", "target": "need", "value": 4},
		{"source": "coronavirus", "target": "since", "value": 4},
		{"source": "coronavirus", "target": "flu", "value": 4},
		{"source": "coronavirus", "target": "situation", "value": 4},
		{"source": "coronavirus", "target": "time", "value": 4},
		{"source": "coronavirus", "target": "person", "value": 4},
		{"source": "coronavirus", "target": "bad", "value": 4},
		{"source": "coronavirus", "target": "also", "value": 4},
		{"source": "smell", "target": "orde", "value": 4},
		{"source": "smell", "target": "worry", "value": 4},
		{"source": "smell", "target": "cough", "value": 4},
		{"source": "smell", "target": "know", "value": 4},
		{"source": "smell", "target": "severe", "value": 4},
		{"source": "smell", "target": "id", "value": 4},
		{"source": "smell", "target": "shit", "value": 4},
		{"source": "smell", "target": "anything", "value": 4},
		{"source": "smell", "target": "fast", "value": 4},
		{"source": "smell", "target": "play", "value": 4},
		{"source": "smell", "target": "since", "value": 4},
		{"source": "smell", "target": "gave", "value": 4},
		{"source": "smell", "target": "simila", "value": 4},
		{"source": "smell", "target": "ive", "value": 4},
		{"source": "smell", "target": "smoke", "value": 4},
		{"source": "smell", "target": "cannot", "value": 4},
		{"source": "smell", "target": "old", "value": 4},
		{"source": "smell", "target": "corona", "value": 4},
		{"source": "smell", "target": "groceries", "value": 4},
		{"source": "smell", "target": "found", "value": 4},
		{"source": "taste", "target": "smoke", "value": 4},
		{"source": "taste", "target": "stress", "value": 4},
		{"source": "taste", "target": "weeks", "value": 4},
		{"source": "taste", "target": "id", "value": 4},
		{"source": "taste", "target": "top", "value": 4},
		{"source": "taste", "target": "anothe", "value": 4},
		{"source": "taste", "target": "late", "value": 4},
		{"source": "taste", "target": "long", "value": 4},
		{"source": "taste", "target": "pape", "value": 4},
		{"source": "taste", "target": "last", "value": 4},
		{"source": "taste", "target": "caught", "value": 4},
		{"source": "taste", "target": "got", "value": 4},
		{"source": "taste", "target": "talk", "value": 4},
		{"source": "taste", "target": "else", "value": 4},
		{"source": "taste", "target": "completely", "value": 4},
		{"source": "taste", "target": "ago", "value": 4},
		{"source": "taste", "target": "covid", "value": 4},
		{"source": "taste", "target": "control", "value": 4},
		{"source": "taste", "target": "hate", "value": 4},
		{"source": "taste", "target": "end", "value": 4},
		{"source": "symptoms", "target": "us", "value": 4},
		{"source": "symptoms", "target": "people", "value": 4},
		{"source": "symptoms", "target": "thei", "value": 4},
		{"source": "symptoms", "target": "someone", "value": 4},
		{"source": "symptoms", "target": "getting", "value": 4},
		{"source": "symptoms", "target": "first", "value": 4},
		{"source": "symptoms", "target": "virus", "value": 4},
		{"source": "symptoms", "target": "even", "value": 4},
		{"source": "symptoms", "target": "may", "value": 4},
		{"source": "symptoms", "target": "many", "value": 4},
		{"source": "symptoms", "target": "flu", "value": 4},
		{"source": "symptoms", "target": "already", "value": 4},
		{"source": "symptoms", "target": "live", "value": 4},
		{"source": "symptoms", "target": "ou", "value": 4},
		{"source": "symptoms", "target": "bad", "value": 4},
		{"source": "symptoms", "target": "probably", "value": 4},
		{"source": "symptoms", "target": "ove", "value": 4},
		{"source": "symptoms", "target": "come", "value": 4},
		{"source": "symptoms", "target": "last", "value": 4},
		{"source": "symptoms", "target": "fo", "value": 4},
		{"source": "negative", "target": "lives", "value": 4},
		{"source": "negative", "target": "making", "value": 4},
		{"source": "negative", "target": "many", "value": 4},
		{"source": "negative", "target": "new", "value": 4},
		{"source": "negative", "target": "taking", "value": 4},
		{"source": "negative", "target": "good", "value": 4},
		{"source": "negative", "target": "sleep", "value": 4},
		{"source": "negative", "target": "trying", "value": 4},
		{"source": "negative", "target": "around", "value": 4},
		{"source": "negative", "target": "put", "value": 4},
		{"source": "negative", "target": "love", "value": 4},
		{"source": "negative", "target": "two", "value": 4},
		{"source": "negative", "target": "life", "value": 4},
		{"source": "negative", "target": "home", "value": 4},
		{"source": "negative", "target": "everyone", "value": 4},
		{"source": "negative", "target": "im", "value": 4},
		{"source": "negative", "target": "afte", "value": 4},
		{"source": "negative", "target": "family", "value": 4},
		{"source": "negative", "target": "food", "value": 4},
		{"source": "negative", "target": "one", "value": 4}
	]
}
