var graph = {
	"nodes": [
		{"id": "COVID", "group": 1},
		{"id": "fl", "group": 1},
		{"id": "context", "group": 1},
		{"id": "link", "group": 1},
		{"id": "sites", "group": 1},
		{"id": "ajg", "group": 1},
		{"id": "click", "group": 1},
		{"id": "title", "group": 1},
		{"id": "fwww", "group": 1},
		{"id": "comments", "group": 1},
		{"id": "html", "group": 1},
		{"id": "article", "group": 1},
		{"id": "nlm", "group": 1},
		{"id": "ncov", "group": 1},
		{"id": "utc", "group": 1},
		{"id": "bko", "group": 1},
		{"id": "blink", "group": 1},
		{"id": "bhttps", "group": 1},
		{"id": "pubmed", "group": 1},
		{"id": "http", "group": 1},
		{"id": "reminders", "group": 1},
		{"id": "positive", "group": 2},
		{"id": "presumptive", "group": 2},
		{"id": "testing", "group": 2},
		{"id": "patients", "group": 2},
		{"id": "covid", "group": 2},
		{"id": "docto", "group": 2},
		{"id": "department", "group": 2},
		{"id": "local", "group": 2},
		{"id": "hotline", "group": 2},
		{"id": "kits", "group": 2},
		{"id": "tag", "group": 2},
		{"id": "thei", "group": 2},
		{"id": "ou", "group": 2},
		{"id": "someone", "group": 2},
		{"id": "says", "group": 2},
		{"id": "match", "group": 2},
		{"id": "share", "group": 2},
		{"id": "novel", "group": 2},
		{"id": "read", "group": 2},
		{"id": "facebook", "group": 2},
		{"id": "fcomments", "group": 2},
		{"id": "coronavirus", "group": 3},
		{"id": "org", "group": 3},
		{"id": "np", "group": 3},
		{"id": "reddit", "group": 3},
		{"id": "message", "group": 3},
		{"id": "youtu", "group": 3},
		{"id": "utm_source", "group": 3},
		{"id": "subject", "group": 3},
		{"id": "delete", "group": 3},
		{"id": "nytimes", "group": 3},
		{"id": "wolframalpha", "group": 3},
		{"id": "remind", "group": 3},
		{"id": "comments", "group": 3},
		{"id": "gov", "group": 3},
		{"id": "jpg", "group": 3},
		{"id": "cnn", "group": 3},
		{"id": "reminde", "group": 3},
		{"id": "en", "group": 3},
		{"id": "compose", "group": 3},
		{"id": "vh", "group": 3},
		{"id": "tech", "group": 3},
		{"id": "smell", "group": 4},
		{"id": "taste", "group": 4},
		{"id": "sense", "group": 4},
		{"id": "lost", "group": 4},
		{"id": "randomly", "group": 4},
		{"id": "half", "group": 4},
		{"id": "disappeared", "group": 4},
		{"id": "senses", "group": 4},
		{"id": "developing", "group": 4},
		{"id": "february", "group": 4},
		{"id": "thursday", "group": 4},
		{"id": "spiked", "group": 4},
		{"id": "ish", "group": 4},
		{"id": "onset", "group": 4},
		{"id": "early", "group": 4},
		{"id": "issues", "group": 4},
		{"id": "one", "group": 4},
		{"id": "fou", "group": 4},
		{"id": "tongue", "group": 4},
		{"id": "gastro", "group": 4},
		{"id": "beginning", "group": 4},
		{"id": "taste", "group": 5},
		{"id": "smell", "group": 5},
		{"id": "sense", "group": 5},
		{"id": "lost", "group": 5},
		{"id": "senses", "group": 5},
		{"id": "randomly", "group": 5},
		{"id": "seemingly", "group": 5},
		{"id": "appetite", "group": 5},
		{"id": "disappeared", "group": 5},
		{"id": "half", "group": 5},
		{"id": "onset", "group": 5},
		{"id": "thursday", "group": 5},
		{"id": "gastro", "group": 5},
		{"id": "early", "group": 5},
		{"id": "diahrea", "group": 5},
		{"id": "fou", "group": 5},
		{"id": "tongue", "group": 5},
		{"id": "spiked", "group": 5},
		{"id": "identical", "group": 5},
		{"id": "one", "group": 5},
		{"id": "february", "group": 5},
		{"id": "symptoms", "group": 6},
		{"id": "since", "group": 6},
		{"id": "went", "group": 6},
		{"id": "couple", "group": 6},
		{"id": "afte", "group": 6},
		{"id": "ive", "group": 6},
		{"id": "mild", "group": 6},
		{"id": "diarrhea", "group": 6},
		{"id": "night", "group": 6},
		{"id": "first", "group": 6},
		{"id": "two", "group": 6},
		{"id": "runny", "group": 6},
		{"id": "nose", "group": 6},
		{"id": "grade", "group": 6},
		{"id": "past", "group": 6},
		{"id": "headache", "group": 6},
		{"id": "woke", "group": 6},
		{"id": "coughing", "group": 6},
		{"id": "week", "group": 6},
		{"id": "slight", "group": 6},
		{"id": "feve", "group": 6},
		{"id": "negative", "group": 7},
		{"id": "waiting", "group": 7},
		{"id": "come", "group": 7},
		{"id": "results", "group": 7},
		{"id": "think", "group": 7},
		{"id": "didnt", "group": 7},
		{"id": "awaiting", "group": 7},
		{"id": "yet", "group": 7},
		{"id": "hospital", "group": 7},
		{"id": "sure", "group": 7},
		{"id": "warrant", "group": 7},
		{"id": "wait", "group": 7},
		{"id": "even", "group": 7},
		{"id": "shot", "group": 7},
		{"id": "husband", "group": 7},
		{"id": "refused", "group": 7},
		{"id": "quarantined", "group": 7},
		{"id": "least", "group": 7},
		{"id": "stayed", "group": 7},
		{"id": "able", "group": 7},
		{"id": "winte", "group": 7}
	],
	"links": [
		{"source": "COVID", "target": "fl", "value": 4},
		{"source": "COVID", "target": "context", "value": 3},
		{"source": "COVID", "target": "link", "value": 3},
		{"source": "COVID", "target": "sites", "value": 3},
		{"source": "COVID", "target": "ajg", "value": 3},
		{"source": "COVID", "target": "click", "value": 3},
		{"source": "COVID", "target": "title", "value": 3},
		{"source": "COVID", "target": "fwww", "value": 3},
		{"source": "COVID", "target": "comments", "value": 3},
		{"source": "COVID", "target": "html", "value": 3},
		{"source": "COVID", "target": "article", "value": 3},
		{"source": "COVID", "target": "nlm", "value": 3},
		{"source": "COVID", "target": "ncov", "value": 3},
		{"source": "COVID", "target": "utc", "value": 3},
		{"source": "COVID", "target": "bko", "value": 3},
		{"source": "COVID", "target": "blink", "value": 3},
		{"source": "COVID", "target": "bhttps", "value": 3},
		{"source": "COVID", "target": "pubmed", "value": 3},
		{"source": "COVID", "target": "http", "value": 3},
		{"source": "COVID", "target": "reminders", "value": 3},
		{"source": "positive", "target": "presumptive", "value": 2},
		{"source": "positive", "target": "testing", "value": 2},
		{"source": "positive", "target": "patients", "value": 2},
		{"source": "positive", "target": "covid", "value": 2},
		{"source": "positive", "target": "docto", "value": 2},
		{"source": "positive", "target": "department", "value": 2},
		{"source": "positive", "target": "local", "value": 2},
		{"source": "positive", "target": "hotline", "value": 2},
		{"source": "positive", "target": "kits", "value": 2},
		{"source": "positive", "target": "tag", "value": 1},
		{"source": "positive", "target": "thei", "value": 1},
		{"source": "positive", "target": "ou", "value": 1},
		{"source": "positive", "target": "someone", "value": 1},
		{"source": "positive", "target": "says", "value": 1},
		{"source": "positive", "target": "match", "value": 1},
		{"source": "positive", "target": "share", "value": 1},
		{"source": "positive", "target": "novel", "value": 1},
		{"source": "positive", "target": "read", "value": 1},
		{"source": "positive", "target": "facebook", "value": 1},
		{"source": "positive", "target": "fcomments", "value": 1},
		{"source": "coronavirus", "target": "org", "value": 4},
		{"source": "coronavirus", "target": "np", "value": 4},
		{"source": "coronavirus", "target": "reddit", "value": 4},
		{"source": "coronavirus", "target": "message", "value": 4},
		{"source": "coronavirus", "target": "youtu", "value": 4},
		{"source": "coronavirus", "target": "utm_source", "value": 4},
		{"source": "coronavirus", "target": "subject", "value": 4},
		{"source": "coronavirus", "target": "delete", "value": 4},
		{"source": "coronavirus", "target": "nytimes", "value": 4},
		{"source": "coronavirus", "target": "wolframalpha", "value": 4},
		{"source": "coronavirus", "target": "remind", "value": 4},
		{"source": "coronavirus", "target": "comments", "value": 4},
		{"source": "coronavirus", "target": "gov", "value": 4},
		{"source": "coronavirus", "target": "jpg", "value": 4},
		{"source": "coronavirus", "target": "cnn", "value": 4},
		{"source": "coronavirus", "target": "reminde", "value": 4},
		{"source": "coronavirus", "target": "en", "value": 4},
		{"source": "coronavirus", "target": "compose", "value": 4},
		{"source": "coronavirus", "target": "vh", "value": 4},
		{"source": "coronavirus", "target": "tech", "value": 4},
		{"source": "smell", "target": "taste", "value": 4},
		{"source": "smell", "target": "sense", "value": 3},
		{"source": "smell", "target": "lost", "value": 3},
		{"source": "smell", "target": "randomly", "value": 3},
		{"source": "smell", "target": "half", "value": 3},
		{"source": "smell", "target": "disappeared", "value": 3},
		{"source": "smell", "target": "senses", "value": 3},
		{"source": "smell", "target": "developing", "value": 3},
		{"source": "smell", "target": "february", "value": 3},
		{"source": "smell", "target": "thursday", "value": 3},
		{"source": "smell", "target": "spiked", "value": 3},
		{"source": "smell", "target": "ish", "value": 3},
		{"source": "smell", "target": "onset", "value": 3},
		{"source": "smell", "target": "early", "value": 3},
		{"source": "smell", "target": "issues", "value": 3},
		{"source": "smell", "target": "one", "value": 3},
		{"source": "smell", "target": "fou", "value": 3},
		{"source": "smell", "target": "tongue", "value": 3},
		{"source": "smell", "target": "gastro", "value": 3},
		{"source": "smell", "target": "beginning", "value": 3},
		{"source": "taste", "target": "smell", "value": 4},
		{"source": "taste", "target": "sense", "value": 4},
		{"source": "taste", "target": "lost", "value": 4},
		{"source": "taste", "target": "senses", "value": 3},
		{"source": "taste", "target": "randomly", "value": 3},
		{"source": "taste", "target": "seemingly", "value": 3},
		{"source": "taste", "target": "appetite", "value": 3},
		{"source": "taste", "target": "disappeared", "value": 3},
		{"source": "taste", "target": "half", "value": 3},
		{"source": "taste", "target": "onset", "value": 3},
		{"source": "taste", "target": "thursday", "value": 3},
		{"source": "taste", "target": "gastro", "value": 3},
		{"source": "taste", "target": "early", "value": 3},
		{"source": "taste", "target": "diahrea", "value": 3},
		{"source": "taste", "target": "fou", "value": 3},
		{"source": "taste", "target": "tongue", "value": 3},
		{"source": "taste", "target": "spiked", "value": 3},
		{"source": "taste", "target": "identical", "value": 3},
		{"source": "taste", "target": "one", "value": 3},
		{"source": "taste", "target": "february", "value": 3},
		{"source": "symptoms", "target": "since", "value": 4},
		{"source": "symptoms", "target": "went", "value": 4},
		{"source": "symptoms", "target": "couple", "value": 4},
		{"source": "symptoms", "target": "afte", "value": 4},
		{"source": "symptoms", "target": "ive", "value": 4},
		{"source": "symptoms", "target": "mild", "value": 4},
		{"source": "symptoms", "target": "diarrhea", "value": 4},
		{"source": "symptoms", "target": "night", "value": 4},
		{"source": "symptoms", "target": "first", "value": 4},
		{"source": "symptoms", "target": "two", "value": 4},
		{"source": "symptoms", "target": "runny", "value": 4},
		{"source": "symptoms", "target": "nose", "value": 4},
		{"source": "symptoms", "target": "grade", "value": 4},
		{"source": "symptoms", "target": "past", "value": 4},
		{"source": "symptoms", "target": "headache", "value": 4},
		{"source": "symptoms", "target": "woke", "value": 4},
		{"source": "symptoms", "target": "coughing", "value": 4},
		{"source": "symptoms", "target": "week", "value": 4},
		{"source": "symptoms", "target": "slight", "value": 4},
		{"source": "symptoms", "target": "feve", "value": 4},
		{"source": "negative", "target": "waiting", "value": 4},
		{"source": "negative", "target": "come", "value": 4},
		{"source": "negative", "target": "results", "value": 4},
		{"source": "negative", "target": "think", "value": 4},
		{"source": "negative", "target": "didnt", "value": 4},
		{"source": "negative", "target": "awaiting", "value": 4},
		{"source": "negative", "target": "yet", "value": 4},
		{"source": "negative", "target": "hospital", "value": 4},
		{"source": "negative", "target": "sure", "value": 4},
		{"source": "negative", "target": "warrant", "value": 4},
		{"source": "negative", "target": "wait", "value": 4},
		{"source": "negative", "target": "even", "value": 4},
		{"source": "negative", "target": "shot", "value": 4},
		{"source": "negative", "target": "husband", "value": 4},
		{"source": "negative", "target": "refused", "value": 4},
		{"source": "negative", "target": "quarantined", "value": 4},
		{"source": "negative", "target": "least", "value": 4},
		{"source": "negative", "target": "stayed", "value": 4},
		{"source": "negative", "target": "able", "value": 4},
		{"source": "negative", "target": "winte", "value": 4}
	]
}
