var graph_positive = {
	"nodes": [
		{"id": "covid", "group": 1},
		{"id": "covid19", "group": 1},
		{"id": "corona", "group": 1},
		{"id": "coronavirus", "group": 1},
		{"id": "virus", "group": 1},
		{"id": "c19", "group": 1},
		{"id": "illness", "group": 1},
		{"id": "sick", "group": 1},
		{"id": "noncovid", "group": 1},
		{"id": "suspected", "group": 1},
		{"id": "mono", "group": 1},
		{"id": "asymptomatic", "group": 1},
		{"id": "reinfected", "group": 1},
		{"id": "suspect", "group": 1},
		{"id": "hospitalised", "group": 1},
		{"id": "influenza", "group": 1},
		{"id": "flu", "group": 1},
		{"id": "hospitalized", "group": 1},
		{"id": "bronchitis", "group": 1},
		{"id": "pneumonia", "group": 1},
		{"id": "officially", "group": 1},
		{"id": "positive", "group": 2},
		{"id": "negative", "group": 2},
		{"id": "postive", "group": 2},
		{"id": "neg", "group": 2},
		{"id": "pos", "group": 2},
		{"id": "symptomatic", "group": 2},
		{"id": "quarantined", "group": 2},
		{"id": "exposed", "group": 2},
		{"id": "exposure", "group": 2},
		{"id": "positives", "group": 2},
		{"id": "positiv", "group": 2},
		{"id": "isolated", "group": 2},
		{"id": "pc", "group": 2},
		{"id": "date", "group": 2},
		{"id": "quarantine", "group": 2},
		{"id": "waiting", "group": 2},
		{"id": "contagious", "group": 2},
		{"id": "displaying", "group": 2},
		{"id": "awaiting", "group": 2},
		{"id": "negatives", "group": 2},
		{"id": "sars", "group": 3},
		{"id": "coronaviruses", "group": 3},
		{"id": "hiv", "group": 3},
		{"id": "sarscov2", "group": 3},
		{"id": "mers", "group": 3},
		{"id": "epidemic", "group": 3},
		{"id": "sars2", "group": 3},
		{"id": "wuhan", "group": 3},
		{"id": "virulent", "group": 3},
		{"id": "strains", "group": 3},
		{"id": "viruses", "group": 3},
		{"id": "cov", "group": 3},
		{"id": "ebv", "group": 3},
		{"id": "sarscov1", "group": 3},
		{"id": "genetically", "group": 3},
		{"id": "smell", "group": 4},
		{"id": "smelltaste", "group": 4},
		{"id": "tastesmell", "group": 4},
		{"id": "senses", "group": 4},
		{"id": "taste", "group": 4},
		{"id": "smelling", "group": 4},
		{"id": "smells", "group": 4},
		{"id": "scent", "group": 4},
		{"id": "muted", "group": 4},
		{"id": "buds", "group": 4},
		{"id": "tasting", "group": 4},
		{"id": "appetite", "group": 4},
		{"id": "metallic", "group": 4},
		{"id": "flavo", "group": 4},
		{"id": "flavors", "group": 4},
		{"id": "sweetness", "group": 4},
		{"id": "saltiness", "group": 4},
		{"id": "scents", "group": 4},
		{"id": "smelled", "group": 4},
		{"id": "partial", "group": 4},
		{"id": "tasted", "group": 4},
		{"id": "tatse", "group": 5},
		{"id": "tastes", "group": 5},
		{"id": "aftertaste", "group": 5},
		{"id": "ammonia", "group": 5},
		{"id": "faintly", "group": 5},
		{"id": "poop", "group": 5},
		{"id": "smokey", "group": 5},
		{"id": "symptoms", "group": 6},
		{"id": "symptom", "group": 6},
		{"id": "issues", "group": 6},
		{"id": "persistent", "group": 6},
		{"id": "howeve", "group": 6},
		{"id": "sob", "group": 6},
		{"id": "fevers", "group": 6},
		{"id": "signs", "group": 6},
		{"id": "symtoms", "group": 6},
		{"id": "symtpoms", "group": 6},
		{"id": "feve", "group": 6},
		{"id": "period", "group": 6},
		{"id": "case", "group": 6},
		{"id": "coughs", "group": 6},
		{"id": "headaches", "group": 6},
		{"id": "cough", "group": 6},
		{"id": "fever", "group": 6},
		{"id": "version", "group": 6},
		{"id": "sickness", "group": 6},
		{"id": "rapid", "group": 7},
		{"id": "patently", "group": 7},
		{"id": "results", "group": 7},
		{"id": "positivesnegatives", "group": 7},
		{"id": "negs", "group": 7},
		{"id": "inconclusive", "group": 7},
		{"id": "antibody", "group": 7}
	],
	"links": [
		{"source": "covid", "target": "covid19", "value": 3},
		{"source": "covid", "target": "corona", "value": 3},
		{"source": "covid", "target": "coronavirus", "value": 3},
		{"source": "covid", "target": "virus", "value": 2},
		{"source": "covid", "target": "c19", "value": 2},
		{"source": "covid", "target": "illness", "value": 2},
		{"source": "covid", "target": "sick", "value": 2},
		{"source": "covid", "target": "noncovid", "value": 2},
		{"source": "covid", "target": "suspected", "value": 2},
		{"source": "covid", "target": "mono", "value": 2},
		{"source": "covid", "target": "asymptomatic", "value": 2},
		{"source": "covid", "target": "reinfected", "value": 2},
		{"source": "covid", "target": "suspect", "value": 2},
		{"source": "covid", "target": "hospitalised", "value": 2},
		{"source": "covid", "target": "influenza", "value": 2},
		{"source": "covid", "target": "flu", "value": 2},
		{"source": "covid", "target": "hospitalized", "value": 2},
		{"source": "covid", "target": "bronchitis", "value": 2},
		{"source": "covid", "target": "pneumonia", "value": 2},
		{"source": "covid", "target": "officially", "value": 2},
		{"source": "positive", "target": "negative", "value": 4},
		{"source": "positive", "target": "postive", "value": 3},
		{"source": "positive", "target": "neg", "value": 3},
		{"source": "positive", "target": "pos", "value": 2},
		{"source": "positive", "target": "symptomatic", "value": 2},
		{"source": "positive", "target": "quarantined", "value": 2},
		{"source": "positive", "target": "exposed", "value": 2},
		{"source": "positive", "target": "asymptomatic", "value": 2},
		{"source": "positive", "target": "exposure", "value": 2},
		{"source": "positive", "target": "positives", "value": 2},
		{"source": "positive", "target": "positiv", "value": 2},
		{"source": "positive", "target": "isolated", "value": 2},
		{"source": "positive", "target": "pc", "value": 2},
		{"source": "positive", "target": "date", "value": 2},
		{"source": "positive", "target": "quarantine", "value": 2},
		{"source": "positive", "target": "waiting", "value": 2},
		{"source": "positive", "target": "contagious", "value": 2},
		{"source": "positive", "target": "displaying", "value": 2},
		{"source": "positive", "target": "awaiting", "value": 2},
		{"source": "positive", "target": "negatives", "value": 2},
		{"source": "coronavirus", "target": "covid19", "value": 3},
		{"source": "coronavirus", "target": "sars", "value": 3},
		{"source": "coronavirus", "target": "coronaviruses", "value": 3},
		{"source": "coronavirus", "target": "influenza", "value": 3},
		{"source": "coronavirus", "target": "hiv", "value": 3},
		{"source": "coronavirus", "target": "sarscov2", "value": 3},
		{"source": "coronavirus", "target": "virus", "value": 3},
		{"source": "coronavirus", "target": "mers", "value": 3},
		{"source": "coronavirus", "target": "covid", "value": 3},
		{"source": "coronavirus", "target": "epidemic", "value": 3},
		{"source": "coronavirus", "target": "corona", "value": 3},
		{"source": "coronavirus", "target": "sars2", "value": 3},
		{"source": "coronavirus", "target": "wuhan", "value": 3},
		{"source": "coronavirus", "target": "virulent", "value": 3},
		{"source": "coronavirus", "target": "strains", "value": 3},
		{"source": "coronavirus", "target": "viruses", "value": 3},
		{"source": "coronavirus", "target": "cov", "value": 3},
		{"source": "coronavirus", "target": "ebv", "value": 3},
		{"source": "coronavirus", "target": "sarscov1", "value": 3},
		{"source": "coronavirus", "target": "genetically", "value": 3},
		{"source": "smell", "target": "smelltaste", "value": 3},
		{"source": "smell", "target": "tastesmell", "value": 3},
		{"source": "smell", "target": "senses", "value": 3},
		{"source": "smell", "target": "taste", "value": 3},
		{"source": "smell", "target": "smelling", "value": 2},
		{"source": "smell", "target": "smells", "value": 2},
		{"source": "smell", "target": "scent", "value": 2},
		{"source": "smell", "target": "muted", "value": 2},
		{"source": "smell", "target": "buds", "value": 2},
		{"source": "smell", "target": "tasting", "value": 2},
		{"source": "smell", "target": "appetite", "value": 2},
		{"source": "smell", "target": "metallic", "value": 2},
		{"source": "smell", "target": "flavo", "value": 2},
		{"source": "smell", "target": "flavors", "value": 2},
		{"source": "smell", "target": "sweetness", "value": 2},
		{"source": "smell", "target": "saltiness", "value": 2},
		{"source": "smell", "target": "scents", "value": 2},
		{"source": "smell", "target": "smelled", "value": 2},
		{"source": "smell", "target": "partial", "value": 2},
		{"source": "smell", "target": "tasted", "value": 2},
		{"source": "taste", "target": "smelltaste", "value": 3},
		{"source": "taste", "target": "tastesmell", "value": 3},
		{"source": "taste", "target": "appetite", "value": 3},
		{"source": "taste", "target": "smell", "value": 3},
		{"source": "taste", "target": "senses", "value": 3},
		{"source": "taste", "target": "tasting", "value": 2},
		{"source": "taste", "target": "flavo", "value": 2},
		{"source": "taste", "target": "tasted", "value": 2},
		{"source": "taste", "target": "tatse", "value": 2},
		{"source": "taste", "target": "muted", "value": 2},
		{"source": "taste", "target": "smells", "value": 2},
		{"source": "taste", "target": "tastes", "value": 2},
		{"source": "taste", "target": "scent", "value": 2},
		{"source": "taste", "target": "smelling", "value": 2},
		{"source": "taste", "target": "aftertaste", "value": 2},
		{"source": "taste", "target": "ammonia", "value": 2},
		{"source": "taste", "target": "faintly", "value": 2},
		{"source": "taste", "target": "poop", "value": 2},
		{"source": "taste", "target": "smokey", "value": 2},
		{"source": "taste", "target": "smelled", "value": 2},
		{"source": "symptoms", "target": "symptom", "value": 3},
		{"source": "symptoms", "target": "illness", "value": 2},
		{"source": "symptoms", "target": "issues", "value": 2},
		{"source": "symptoms", "target": "persistent", "value": 2},
		{"source": "symptoms", "target": "howeve", "value": 2},
		{"source": "symptoms", "target": "sob", "value": 2},
		{"source": "symptoms", "target": "fevers", "value": 2},
		{"source": "symptoms", "target": "signs", "value": 2},
		{"source": "symptoms", "target": "symtoms", "value": 2},
		{"source": "symptoms", "target": "symtpoms", "value": 2},
		{"source": "symptoms", "target": "feve", "value": 2},
		{"source": "symptoms", "target": "symptomatic", "value": 2},
		{"source": "symptoms", "target": "period", "value": 2},
		{"source": "symptoms", "target": "case", "value": 2},
		{"source": "symptoms", "target": "coughs", "value": 2},
		{"source": "symptoms", "target": "headaches", "value": 2},
		{"source": "symptoms", "target": "cough", "value": 2},
		{"source": "symptoms", "target": "fever", "value": 2},
		{"source": "symptoms", "target": "version", "value": 2},
		{"source": "symptoms", "target": "sickness", "value": 2},
		{"source": "negative", "target": "positive", "value": 4},
		{"source": "negative", "target": "neg", "value": 3},
		{"source": "negative", "target": "negatives", "value": 3},
		{"source": "negative", "target": "postive", "value": 3},
		{"source": "negative", "target": "pc", "value": 2},
		{"source": "negative", "target": "positives", "value": 2},
		{"source": "negative", "target": "pos", "value": 2},
		{"source": "negative", "target": "rapid", "value": 2},
		{"source": "negative", "target": "patently", "value": 2},
		{"source": "negative", "target": "waiting", "value": 2},
		{"source": "negative", "target": "symptomatic", "value": 2},
		{"source": "negative", "target": "quarantined", "value": 2},
		{"source": "negative", "target": "results", "value": 2},
		{"source": "negative", "target": "positivesnegatives", "value": 2},
		{"source": "negative", "target": "awaiting", "value": 2},
		{"source": "negative", "target": "negs", "value": 2},
		{"source": "negative", "target": "inconclusive", "value": 2},
		{"source": "negative", "target": "asymptomatic", "value": 2},
		{"source": "negative", "target": "antibody", "value": 2},
		{"source": "negative", "target": "contagious", "value": 2}
	]
}
