var graph_positive = {
	"nodes": [
		{"id": "covid", "group": 1},
		{"id": "corona", "group": 1},
		{"id": "coronavirus", "group": 1},
		{"id": "virus", "group": 1},
		{"id": "cv", "group": 1},
		{"id": "suspected", "group": 1},
		{"id": "ebv", "group": 1},
		{"id": "asymptotic", "group": 1},
		{"id": "asymptomatic", "group": 1},
		{"id": "mono", "group": 1},
		{"id": "resurgence", "group": 1},
		{"id": "illness", "group": 1},
		{"id": "reinfection", "group": 1},
		{"id": "presenting", "group": 1},
		{"id": "confirmed", "group": 1},
		{"id": "possibility", "group": 1},
		{"id": "influenza", "group": 1},
		{"id": "reinfected", "group": 1},
		{"id": "hospitalized", "group": 1},
		{"id": "exhibiting", "group": 1},
		{"id": "exhibit", "group": 1},
		{"id": "positive", "group": 2},
		{"id": "negative", "group": 2},
		{"id": "postive", "group": 2},
		{"id": "exposed", "group": 2},
		{"id": "symptomatic", "group": 2},
		{"id": "patently", "group": 2},
		{"id": "neg", "group": 2},
		{"id": "positives", "group": 2},
		{"id": "quarantined", "group": 2},
		{"id": "exposure", "group": 2},
		{"id": "awaiting", "group": 2},
		{"id": "got", "group": 2},
		{"id": "antibodies", "group": 2},
		{"id": "officially", "group": 2},
		{"id": "results", "group": 2},
		{"id": "negatives", "group": 2},
		{"id": "positiv", "group": 2},
		{"id": "contact", "group": 2},
		{"id": "inconclusive", "group": 2},
		{"id": "roommate", "group": 2},
		{"id": "html", "group": 3},
		{"id": "ncov", "group": 3},
		{"id": "nytimes", "group": 3},
		{"id": "epidemic", "group": 3},
		{"id": "mutations", "group": 3},
		{"id": "sars", "group": 3},
		{"id": "vaccines", "group": 3},
		{"id": "statista", "group": 3},
		{"id": "coronaviruses", "group": 3},
		{"id": "hiv", "group": 3},
		{"id": "tuberculosis", "group": 3},
		{"id": "virulent", "group": 3},
		{"id": "exist", "group": 3},
		{"id": "vaccination", "group": 3},
		{"id": "predicting", "group": 3},
		{"id": "endemic", "group": 3},
		{"id": "smell", "group": 4},
		{"id": "senses", "group": 4},
		{"id": "buds", "group": 4},
		{"id": "taste", "group": 4},
		{"id": "metallic", "group": 4},
		{"id": "smelling", "group": 4},
		{"id": "saltiness", "group": 4},
		{"id": "smells", "group": 4},
		{"id": "appetite", "group": 4},
		{"id": "scent", "group": 4},
		{"id": "tasting", "group": 4},
		{"id": "flavo", "group": 4},
		{"id": "sweetness", "group": 4},
		{"id": "muted", "group": 4},
		{"id": "tasted", "group": 4},
		{"id": "flavors", "group": 4},
		{"id": "whiffs", "group": 4},
		{"id": "smelled", "group": 4},
		{"id": "anosmia", "group": 4},
		{"id": "distorted", "group": 4},
		{"id": "scents", "group": 4},
		{"id": "tatse", "group": 5},
		{"id": "faintly", "group": 5},
		{"id": "dulled", "group": 5},
		{"id": "hint", "group": 5},
		{"id": "tastes", "group": 5},
		{"id": "poop", "group": 5},
		{"id": "cologne", "group": 5},
		{"id": "perfume", "group": 5},
		{"id": "symptoms", "group": 6},
		{"id": "symptom", "group": 6},
		{"id": "issues", "group": 6},
		{"id": "sickness", "group": 6},
		{"id": "sob", "group": 6},
		{"id": "feve", "group": 6},
		{"id": "howeve", "group": 6},
		{"id": "illnesses", "group": 6},
		{"id": "symtoms", "group": 6},
		{"id": "signs", "group": 6},
		{"id": "cough", "group": 6},
		{"id": "symtpoms", "group": 6},
		{"id": "fevers", "group": 6},
		{"id": "headaches", "group": 6},
		{"id": "mine", "group": 6},
		{"id": "although", "group": 6},
		{"id": "case", "group": 6},
		{"id": "problems", "group": 6},
		{"id": "experiencing", "group": 6},
		{"id": "diarrhea", "group": 6},
		{"id": "negs", "group": 7},
		{"id": "pc", "group": 7},
		{"id": "antibody", "group": 7},
		{"id": "waiting", "group": 7},
		{"id": "rapid", "group": 7},
		{"id": "contagious", "group": 7}
	],
	"links": [
		{"source": "covid", "target": "corona", "value": 3},
		{"source": "covid", "target": "coronavirus", "value": 3},
		{"source": "covid", "target": "virus", "value": 2},
		{"source": "covid", "target": "cv", "value": 2},
		{"source": "covid", "target": "suspected", "value": 2},
		{"source": "covid", "target": "ebv", "value": 2},
		{"source": "covid", "target": "asymptotic", "value": 2},
		{"source": "covid", "target": "asymptomatic", "value": 2},
		{"source": "covid", "target": "mono", "value": 2},
		{"source": "covid", "target": "resurgence", "value": 2},
		{"source": "covid", "target": "illness", "value": 2},
		{"source": "covid", "target": "reinfection", "value": 2},
		{"source": "covid", "target": "presenting", "value": 2},
		{"source": "covid", "target": "confirmed", "value": 2},
		{"source": "covid", "target": "possibility", "value": 2},
		{"source": "covid", "target": "influenza", "value": 2},
		{"source": "covid", "target": "reinfected", "value": 2},
		{"source": "covid", "target": "hospitalized", "value": 2},
		{"source": "covid", "target": "exhibiting", "value": 2},
		{"source": "covid", "target": "exhibit", "value": 2},
		{"source": "positive", "target": "negative", "value": 4},
		{"source": "positive", "target": "postive", "value": 3},
		{"source": "positive", "target": "exposed", "value": 2},
		{"source": "positive", "target": "symptomatic", "value": 2},
		{"source": "positive", "target": "patently", "value": 2},
		{"source": "positive", "target": "neg", "value": 2},
		{"source": "positive", "target": "asymptomatic", "value": 2},
		{"source": "positive", "target": "positives", "value": 2},
		{"source": "positive", "target": "quarantined", "value": 2},
		{"source": "positive", "target": "exposure", "value": 2},
		{"source": "positive", "target": "awaiting", "value": 2},
		{"source": "positive", "target": "got", "value": 2},
		{"source": "positive", "target": "antibodies", "value": 2},
		{"source": "positive", "target": "officially", "value": 2},
		{"source": "positive", "target": "results", "value": 2},
		{"source": "positive", "target": "negatives", "value": 2},
		{"source": "positive", "target": "positiv", "value": 2},
		{"source": "positive", "target": "contact", "value": 2},
		{"source": "positive", "target": "inconclusive", "value": 2},
		{"source": "positive", "target": "roommate", "value": 2},
		{"source": "coronavirus", "target": "covid", "value": 3},
		{"source": "coronavirus", "target": "html", "value": 3},
		{"source": "coronavirus", "target": "ncov", "value": 2},
		{"source": "coronavirus", "target": "nytimes", "value": 2},
		{"source": "coronavirus", "target": "epidemic", "value": 2},
		{"source": "coronavirus", "target": "mutations", "value": 2},
		{"source": "coronavirus", "target": "exhibit", "value": 2},
		{"source": "coronavirus", "target": "cv", "value": 2},
		{"source": "coronavirus", "target": "sars", "value": 2},
		{"source": "coronavirus", "target": "vaccines", "value": 2},
		{"source": "coronavirus", "target": "corona", "value": 2},
		{"source": "coronavirus", "target": "statista", "value": 2},
		{"source": "coronavirus", "target": "coronaviruses", "value": 2},
		{"source": "coronavirus", "target": "hiv", "value": 2},
		{"source": "coronavirus", "target": "tuberculosis", "value": 2},
		{"source": "coronavirus", "target": "virulent", "value": 2},
		{"source": "coronavirus", "target": "exist", "value": 2},
		{"source": "coronavirus", "target": "vaccination", "value": 2},
		{"source": "coronavirus", "target": "predicting", "value": 2},
		{"source": "coronavirus", "target": "endemic", "value": 2},
		{"source": "smell", "target": "senses", "value": 3},
		{"source": "smell", "target": "buds", "value": 2},
		{"source": "smell", "target": "taste", "value": 2},
		{"source": "smell", "target": "metallic", "value": 2},
		{"source": "smell", "target": "smelling", "value": 2},
		{"source": "smell", "target": "saltiness", "value": 2},
		{"source": "smell", "target": "smells", "value": 2},
		{"source": "smell", "target": "appetite", "value": 2},
		{"source": "smell", "target": "scent", "value": 2},
		{"source": "smell", "target": "tasting", "value": 2},
		{"source": "smell", "target": "flavo", "value": 2},
		{"source": "smell", "target": "sweetness", "value": 2},
		{"source": "smell", "target": "muted", "value": 2},
		{"source": "smell", "target": "tasted", "value": 2},
		{"source": "smell", "target": "flavors", "value": 2},
		{"source": "smell", "target": "whiffs", "value": 2},
		{"source": "smell", "target": "smelled", "value": 2},
		{"source": "smell", "target": "anosmia", "value": 2},
		{"source": "smell", "target": "distorted", "value": 2},
		{"source": "smell", "target": "scents", "value": 2},
		{"source": "taste", "target": "senses", "value": 3},
		{"source": "taste", "target": "appetite", "value": 3},
		{"source": "taste", "target": "tatse", "value": 2},
		{"source": "taste", "target": "smell", "value": 2},
		{"source": "taste", "target": "tasting", "value": 2},
		{"source": "taste", "target": "tasted", "value": 2},
		{"source": "taste", "target": "smells", "value": 2},
		{"source": "taste", "target": "smelling", "value": 2},
		{"source": "taste", "target": "faintly", "value": 2},
		{"source": "taste", "target": "flavo", "value": 2},
		{"source": "taste", "target": "dulled", "value": 2},
		{"source": "taste", "target": "hint", "value": 2},
		{"source": "taste", "target": "muted", "value": 2},
		{"source": "taste", "target": "tastes", "value": 2},
		{"source": "taste", "target": "scent", "value": 2},
		{"source": "taste", "target": "whiffs", "value": 2},
		{"source": "taste", "target": "poop", "value": 2},
		{"source": "taste", "target": "cologne", "value": 2},
		{"source": "taste", "target": "smelled", "value": 2},
		{"source": "taste", "target": "perfume", "value": 2},
		{"source": "symptoms", "target": "symptom", "value": 3},
		{"source": "symptoms", "target": "illness", "value": 2},
		{"source": "symptoms", "target": "issues", "value": 2},
		{"source": "symptoms", "target": "sickness", "value": 2},
		{"source": "symptoms", "target": "sob", "value": 2},
		{"source": "symptoms", "target": "feve", "value": 2},
		{"source": "symptoms", "target": "howeve", "value": 2},
		{"source": "symptoms", "target": "illnesses", "value": 2},
		{"source": "symptoms", "target": "symtoms", "value": 2},
		{"source": "symptoms", "target": "signs", "value": 2},
		{"source": "symptoms", "target": "cough", "value": 2},
		{"source": "symptoms", "target": "symtpoms", "value": 2},
		{"source": "symptoms", "target": "fevers", "value": 2},
		{"source": "symptoms", "target": "headaches", "value": 2},
		{"source": "symptoms", "target": "mine", "value": 2},
		{"source": "symptoms", "target": "although", "value": 2},
		{"source": "symptoms", "target": "case", "value": 2},
		{"source": "symptoms", "target": "problems", "value": 2},
		{"source": "symptoms", "target": "experiencing", "value": 2},
		{"source": "symptoms", "target": "diarrhea", "value": 2},
		{"source": "negative", "target": "positive", "value": 4},
		{"source": "negative", "target": "neg", "value": 3},
		{"source": "negative", "target": "negatives", "value": 3},
		{"source": "negative", "target": "postive", "value": 3},
		{"source": "negative", "target": "patently", "value": 2},
		{"source": "negative", "target": "positives", "value": 2},
		{"source": "negative", "target": "negs", "value": 2},
		{"source": "negative", "target": "pc", "value": 2},
		{"source": "negative", "target": "inconclusive", "value": 2},
		{"source": "negative", "target": "antibody", "value": 2},
		{"source": "negative", "target": "awaiting", "value": 2},
		{"source": "negative", "target": "results", "value": 2},
		{"source": "negative", "target": "got", "value": 2},
		{"source": "negative", "target": "waiting", "value": 2},
		{"source": "negative", "target": "exposed", "value": 2},
		{"source": "negative", "target": "symptomatic", "value": 2},
		{"source": "negative", "target": "rapid", "value": 2},
		{"source": "negative", "target": "contagious", "value": 2},
		{"source": "negative", "target": "antibodies", "value": 2},
		{"source": "negative", "target": "asymptomatic", "value": 2}
	]
}
