var graph_support = {
	"nodes": [
		{"id": "covid", "group": 1},
		{"id": "showing", "group": 1},
		{"id": "disease", "group": 1},
		{"id": "blood", "group": 1},
		{"id": "false", "group": 1},
		{"id": "testing", "group": 1},
		{"id": "tests", "group": 1},
		{"id": "infection", "group": 1},
		{"id": "negatives", "group": 1},
		{"id": "antibody", "group": 1},
		{"id": "severe", "group": 1},
		{"id": "patients", "group": 1},
		{"id": "coronavirus", "group": 1},
		{"id": "viral", "group": 1},
		{"id": "respiratory", "group": 1},
		{"id": "damage", "group": 1},
		{"id": "mild", "group": 1},
		{"id": "rates", "group": 1},
		{"id": "show", "group": 1},
		{"id": "potential", "group": 1},
		{"id": "result", "group": 1},
		{"id": "positive", "group": 2},
		{"id": "negative", "group": 2},
		{"id": "results", "group": 2},
		{"id": "test", "group": 2},
		{"id": "tested", "group": 2},
		{"id": "antibodies", "group": 2},
		{"id": "strep", "group": 2},
		{"id": "presume", "group": 2},
		{"id": "waiting", "group": 2},
		{"id": "discharged", "group": 2},
		{"id": "presumed", "group": 2},
		{"id": "coworke", "group": 2},
		{"id": "develop", "group": 2},
		{"id": "recovering", "group": 2},
		{"id": "exposed", "group": 2},
		{"id": "html", "group": 3},
		{"id": "org", "group": 3},
		{"id": "uk", "group": 3},
		{"id": "nhs", "group": 3},
		{"id": "uploads", "group": 3},
		{"id": "gov", "group": 3},
		{"id": "intl", "group": 3},
		{"id": "www", "group": 3},
		{"id": "cebm", "group": 3},
		{"id": "https", "group": 3},
		{"id": "webmd", "group": 3},
		{"id": "newscientist", "group": 3},
		{"id": "net", "group": 3},
		{"id": "edu", "group": 3},
		{"id": "healthdata", "group": 3},
		{"id": "clinicaltrials", "group": 3},
		{"id": "tulane", "group": 3},
		{"id": "pdf", "group": 3},
		{"id": "cdc", "group": 3},
		{"id": "index", "group": 3},
		{"id": "smell", "group": 4},
		{"id": "taste", "group": 4},
		{"id": "chest", "group": 4},
		{"id": "scratchy", "group": 4},
		{"id": "woke", "group": 4},
		{"id": "pain", "group": 4},
		{"id": "happened", "group": 4},
		{"id": "exact", "group": 4},
		{"id": "sore", "group": 4},
		{"id": "tickle", "group": 4},
		{"id": "weird", "group": 4},
		{"id": "tightness", "group": 4},
		{"id": "yesterday", "group": 4},
		{"id": "tired", "group": 4},
		{"id": "headache", "group": 4},
		{"id": "thought", "group": 4},
		{"id": "youve", "group": 4},
		{"id": "tickled", "group": 4},
		{"id": "throat", "group": 4},
		{"id": "rough", "group": 4},
		{"id": "clearing", "group": 4},
		{"id": "turned", "group": 5},
		{"id": "almost", "group": 5},
		{"id": "symptoms", "group": 6},
		{"id": "feve", "group": 6},
		{"id": "pneumonia", "group": 6},
		{"id": "symptom", "group": 6},
		{"id": "cough", "group": 6},
		{"id": "allergies", "group": 6},
		{"id": "cold", "group": 6},
		{"id": "allergy", "group": 6},
		{"id": "hay", "group": 6},
		{"id": "shortness", "group": 6},
		{"id": "recovered", "group": 6},
		{"id": "persistent", "group": 6},
		{"id": "fever", "group": 6},
		{"id": "retested", "group": 7},
		{"id": "gotten", "group": 7},
		{"id": "swab", "group": 7},
		{"id": "came", "group": 7},
		{"id": "recove", "group": 7}
	],
	"links": [
		{"source": "covid", "target": "showing", "value": 4},
		{"source": "covid", "target": "disease", "value": 4},
		{"source": "covid", "target": "blood", "value": 4},
		{"source": "covid", "target": "false", "value": 4},
		{"source": "covid", "target": "testing", "value": 4},
		{"source": "covid", "target": "tests", "value": 4},
		{"source": "covid", "target": "infection", "value": 4},
		{"source": "covid", "target": "negatives", "value": 3},
		{"source": "covid", "target": "antibody", "value": 3},
		{"source": "covid", "target": "severe", "value": 3},
		{"source": "covid", "target": "patients", "value": 3},
		{"source": "covid", "target": "coronavirus", "value": 3},
		{"source": "covid", "target": "viral", "value": 3},
		{"source": "covid", "target": "respiratory", "value": 3},
		{"source": "covid", "target": "damage", "value": 3},
		{"source": "covid", "target": "mild", "value": 3},
		{"source": "covid", "target": "rates", "value": 3},
		{"source": "covid", "target": "show", "value": 3},
		{"source": "covid", "target": "potential", "value": 3},
		{"source": "covid", "target": "result", "value": 3},
		{"source": "positive", "target": "negative", "value": 4},
		{"source": "positive", "target": "results", "value": 4},
		{"source": "positive", "target": "test", "value": 4},
		{"source": "positive", "target": "antibody", "value": 3},
		{"source": "positive", "target": "tested", "value": 3},
		{"source": "positive", "target": "result", "value": 3},
		{"source": "positive", "target": "antibodies", "value": 3},
		{"source": "positive", "target": "false", "value": 3},
		{"source": "positive", "target": "strep", "value": 3},
		{"source": "positive", "target": "tests", "value": 3},
		{"source": "positive", "target": "presume", "value": 3},
		{"source": "positive", "target": "negatives", "value": 3},
		{"source": "positive", "target": "waiting", "value": 3},
		{"source": "positive", "target": "discharged", "value": 3},
		{"source": "positive", "target": "presumed", "value": 3},
		{"source": "positive", "target": "testing", "value": 3},
		{"source": "positive", "target": "coworke", "value": 3},
		{"source": "positive", "target": "develop", "value": 3},
		{"source": "positive", "target": "recovering", "value": 3},
		{"source": "positive", "target": "exposed", "value": 3},
		{"source": "coronavirus", "target": "html", "value": 4},
		{"source": "coronavirus", "target": "org", "value": 4},
		{"source": "coronavirus", "target": "uk", "value": 4},
		{"source": "coronavirus", "target": "nhs", "value": 4},
		{"source": "coronavirus", "target": "uploads", "value": 4},
		{"source": "coronavirus", "target": "gov", "value": 4},
		{"source": "coronavirus", "target": "intl", "value": 4},
		{"source": "coronavirus", "target": "www", "value": 4},
		{"source": "coronavirus", "target": "cebm", "value": 4},
		{"source": "coronavirus", "target": "https", "value": 4},
		{"source": "coronavirus", "target": "webmd", "value": 4},
		{"source": "coronavirus", "target": "newscientist", "value": 4},
		{"source": "coronavirus", "target": "net", "value": 4},
		{"source": "coronavirus", "target": "edu", "value": 4},
		{"source": "coronavirus", "target": "healthdata", "value": 4},
		{"source": "coronavirus", "target": "clinicaltrials", "value": 4},
		{"source": "coronavirus", "target": "tulane", "value": 4},
		{"source": "coronavirus", "target": "pdf", "value": 4},
		{"source": "coronavirus", "target": "cdc", "value": 4},
		{"source": "coronavirus", "target": "index", "value": 4},
		{"source": "smell", "target": "taste", "value": 4},
		{"source": "smell", "target": "chest", "value": 4},
		{"source": "smell", "target": "scratchy", "value": 4},
		{"source": "smell", "target": "woke", "value": 4},
		{"source": "smell", "target": "pain", "value": 4},
		{"source": "smell", "target": "happened", "value": 4},
		{"source": "smell", "target": "exact", "value": 4},
		{"source": "smell", "target": "sore", "value": 4},
		{"source": "smell", "target": "tickle", "value": 4},
		{"source": "smell", "target": "weird", "value": 4},
		{"source": "smell", "target": "tightness", "value": 4},
		{"source": "smell", "target": "yesterday", "value": 3},
		{"source": "smell", "target": "tired", "value": 3},
		{"source": "smell", "target": "headache", "value": 3},
		{"source": "smell", "target": "thought", "value": 3},
		{"source": "smell", "target": "youve", "value": 3},
		{"source": "smell", "target": "tickled", "value": 3},
		{"source": "smell", "target": "throat", "value": 3},
		{"source": "smell", "target": "rough", "value": 3},
		{"source": "smell", "target": "clearing", "value": 3},
		{"source": "taste", "target": "smell", "value": 4},
		{"source": "taste", "target": "happened", "value": 4},
		{"source": "taste", "target": "scratchy", "value": 4},
		{"source": "taste", "target": "woke", "value": 4},
		{"source": "taste", "target": "chest", "value": 4},
		{"source": "taste", "target": "tickle", "value": 4},
		{"source": "taste", "target": "sore", "value": 4},
		{"source": "taste", "target": "tightness", "value": 4},
		{"source": "taste", "target": "pain", "value": 4},
		{"source": "taste", "target": "exact", "value": 4},
		{"source": "taste", "target": "yesterday", "value": 4},
		{"source": "taste", "target": "headache", "value": 4},
		{"source": "taste", "target": "weird", "value": 4},
		{"source": "taste", "target": "turned", "value": 4},
		{"source": "taste", "target": "throat", "value": 4},
		{"source": "taste", "target": "rough", "value": 4},
		{"source": "taste", "target": "thought", "value": 4},
		{"source": "taste", "target": "tired", "value": 4},
		{"source": "taste", "target": "almost", "value": 4},
		{"source": "taste", "target": "tickled", "value": 4},
		{"source": "symptoms", "target": "mild", "value": 4},
		{"source": "symptoms", "target": "feve", "value": 4},
		{"source": "symptoms", "target": "pneumonia", "value": 4},
		{"source": "symptoms", "target": "symptom", "value": 4},
		{"source": "symptoms", "target": "cough", "value": 4},
		{"source": "symptoms", "target": "allergies", "value": 4},
		{"source": "symptoms", "target": "cold", "value": 4},
		{"source": "symptoms", "target": "severe", "value": 4},
		{"source": "symptoms", "target": "negative", "value": 4},
		{"source": "symptoms", "target": "develop", "value": 4},
		{"source": "symptoms", "target": "sore", "value": 3},
		{"source": "symptoms", "target": "allergy", "value": 3},
		{"source": "symptoms", "target": "hay", "value": 3},
		{"source": "symptoms", "target": "shortness", "value": 3},
		{"source": "symptoms", "target": "strep", "value": 3},
		{"source": "symptoms", "target": "recovered", "value": 3},
		{"source": "symptoms", "target": "persistent", "value": 3},
		{"source": "symptoms", "target": "throat", "value": 3},
		{"source": "symptoms", "target": "tests", "value": 3},
		{"source": "symptoms", "target": "fever", "value": 3},
		{"source": "negative", "target": "results", "value": 4},
		{"source": "negative", "target": "test", "value": 4},
		{"source": "negative", "target": "positive", "value": 4},
		{"source": "negative", "target": "tested", "value": 4},
		{"source": "negative", "target": "antibody", "value": 4},
		{"source": "negative", "target": "result", "value": 4},
		{"source": "negative", "target": "strep", "value": 4},
		{"source": "negative", "target": "symptoms", "value": 4},
		{"source": "negative", "target": "antibodies", "value": 4},
		{"source": "negative", "target": "tests", "value": 3},
		{"source": "negative", "target": "develop", "value": 3},
		{"source": "negative", "target": "waiting", "value": 3},
		{"source": "negative", "target": "mild", "value": 3},
		{"source": "negative", "target": "retested", "value": 3},
		{"source": "negative", "target": "gotten", "value": 3},
		{"source": "negative", "target": "swab", "value": 3},
		{"source": "negative", "target": "recovered", "value": 3},
		{"source": "negative", "target": "came", "value": 3},
		{"source": "negative", "target": "negatives", "value": 3},
		{"source": "negative", "target": "recove", "value": 3}
	]
}
