var graph = {
	"nodes": [
		{"id": "covid", "group": 1},
		{"id": "fle", "group": 1},
		{"id": "fldv", "group": 1},
		{"id": "context", "group": 1},
		{"id": "comments", "group": 1},
		{"id": "article", "group": 1},
		{"id": "click", "group": 1},
		{"id": "fcovid", "group": 1},
		{"id": "link", "group": 1},
		{"id": "fwww", "group": 1},
		{"id": "fl", "group": 1},
		{"id": "en", "group": 1},
		{"id": "wolframalpha", "group": 1},
		{"id": "ncbi", "group": 1},
		{"id": "remind", "group": 1},
		{"id": "gov", "group": 1},
		{"id": "http", "group": 1},
		{"id": "jpg", "group": 1},
		{"id": "nlm", "group": 1},
		{"id": "bhttps", "group": 1},
		{"id": "ios_app", "group": 1},
		{"id": "positive", "group": 2},
		{"id": "health", "group": 2},
		{"id": "cdc", "group": 2},
		{"id": "fcomments", "group": 2},
		{"id": "local", "group": 2},
		{"id": "cleveland", "group": 2},
		{"id": "aggravate", "group": 2},
		{"id": "sites", "group": 2},
		{"id": "metro", "group": 2},
		{"id": "tech", "group": 2},
		{"id": "twitte", "group": 2},
		{"id": "status", "group": 2},
		{"id": "heres", "group": 2},
		{"id": "coronavirus", "group": 3},
		{"id": "reddit", "group": 3},
		{"id": "org", "group": 3},
		{"id": "youtu", "group": 3},
		{"id": "utm_source", "group": 3},
		{"id": "imgu", "group": 3},
		{"id": "message", "group": 3},
		{"id": "subject", "group": 3},
		{"id": "np", "group": 3},
		{"id": "amp", "group": 3},
		{"id": "ajg", "group": 3},
		{"id": "redd", "group": 3},
		{"id": "reminde", "group": 3},
		{"id": "forbes", "group": 3},
		{"id": "com", "group": 3},
		{"id": "gallery", "group": 3},
		{"id": "remindmebot", "group": 3},
		{"id": "smell", "group": 4},
		{"id": "taste", "group": 4},
		{"id": "lost", "group": 4},
		{"id": "sense", "group": 4},
		{"id": "ish", "group": 4},
		{"id": "half", "group": 4},
		{"id": "senses", "group": 4},
		{"id": "pronounced", "group": 4},
		{"id": "gi", "group": 4},
		{"id": "loss", "group": 4},
		{"id": "early", "group": 4},
		{"id": "tongue", "group": 4},
		{"id": "flew", "group": 4},
		{"id": "feb", "group": 4},
		{"id": "appetite", "group": 4},
		{"id": "shivering", "group": 4},
		{"id": "recall", "group": 4},
		{"id": "old", "group": 4},
		{"id": "one", "group": 4},
		{"id": "yea", "group": 4},
		{"id": "hou", "group": 4},
		{"id": "fou", "group": 5},
		{"id": "began", "group": 5},
		{"id": "airport", "group": 5},
		{"id": "broke", "group": 5},
		{"id": "nostril", "group": 5},
		{"id": "christmas", "group": 5},
		{"id": "symptoms", "group": 6},
		{"id": "went", "group": 6},
		{"id": "ive", "group": 6},
		{"id": "since", "group": 6},
		{"id": "got", "group": 6},
		{"id": "afte", "group": 6},
		{"id": "back", "group": 6},
		{"id": "couple", "group": 6},
		{"id": "night", "group": 6},
		{"id": "mild", "group": 6},
		{"id": "past", "group": 6},
		{"id": "runny", "group": 6},
		{"id": "day", "group": 6},
		{"id": "coughing", "group": 6},
		{"id": "weeks", "group": 6},
		{"id": "headache", "group": 6},
		{"id": "aches", "group": 6},
		{"id": "almost", "group": 6},
		{"id": "diarrhea", "group": 6},
		{"id": "bad", "group": 6},
		{"id": "friday", "group": 6},
		{"id": "negative", "group": 7},
		{"id": "even", "group": 7},
		{"id": "think", "group": 7},
		{"id": "waiting", "group": 7},
		{"id": "warrant", "group": 7},
		{"id": "told", "group": 7},
		{"id": "wait", "group": 7},
		{"id": "yet", "group": 7},
		{"id": "didnt", "group": 7},
		{"id": "cant", "group": 7},
		{"id": "come", "group": 7},
		{"id": "urgent", "group": 7},
		{"id": "hospital", "group": 7},
		{"id": "exposed", "group": 7},
		{"id": "husband", "group": 7},
		{"id": "winte", "group": 7},
		{"id": "denied", "group": 7},
		{"id": "without", "group": 7},
		{"id": "work", "group": 7},
		{"id": "whilst", "group": 7},
		{"id": "honestly", "group": 7}
	],
	"links": [
		{"source": "covid", "target": "fle", "value": 4},
		{"source": "covid", "target": "fldv", "value": 4},
		{"source": "covid", "target": "context", "value": 4},
		{"source": "covid", "target": "comments", "value": 4},
		{"source": "covid", "target": "article", "value": 4},
		{"source": "covid", "target": "click", "value": 4},
		{"source": "covid", "target": "fcovid", "value": 4},
		{"source": "covid", "target": "link", "value": 4},
		{"source": "covid", "target": "fwww", "value": 4},
		{"source": "covid", "target": "fl", "value": 4},
		{"source": "covid", "target": "en", "value": 4},
		{"source": "covid", "target": "wolframalpha", "value": 4},
		{"source": "covid", "target": "ncbi", "value": 4},
		{"source": "covid", "target": "remind", "value": 4},
		{"source": "covid", "target": "gov", "value": 4},
		{"source": "covid", "target": "http", "value": 3},
		{"source": "covid", "target": "jpg", "value": 3},
		{"source": "covid", "target": "nlm", "value": 3},
		{"source": "covid", "target": "bhttps", "value": 3},
		{"source": "covid", "target": "ios_app", "value": 3},
		{"source": "positive", "target": "covid", "value": 3},
		{"source": "positive", "target": "fldv", "value": 2},
		{"source": "positive", "target": "fle", "value": 1},
		{"source": "positive", "target": "fl", "value": 1},
		{"source": "positive", "target": "health", "value": 1},
		{"source": "positive", "target": "fcovid", "value": 1},
		{"source": "positive", "target": "cdc", "value": 1},
		{"source": "positive", "target": "fcomments", "value": 1},
		{"source": "positive", "target": "local", "value": 1},
		{"source": "positive", "target": "cleveland", "value": 1},
		{"source": "positive", "target": "aggravate", "value": 1},
		{"source": "positive", "target": "sites", "value": 1},
		{"source": "positive", "target": "context", "value": 1},
		{"source": "positive", "target": "metro", "value": 1},
		{"source": "positive", "target": "tech", "value": 1},
		{"source": "positive", "target": "article", "value": 1},
		{"source": "positive", "target": "twitte", "value": 1},
		{"source": "positive", "target": "status", "value": 1},
		{"source": "positive", "target": "heres", "value": 1},
		{"source": "positive", "target": "link", "value": 1},
		{"source": "coronavirus", "target": "reddit", "value": 4},
		{"source": "coronavirus", "target": "org", "value": 4},
		{"source": "coronavirus", "target": "youtu", "value": 4},
		{"source": "coronavirus", "target": "utm_source", "value": 4},
		{"source": "coronavirus", "target": "imgu", "value": 4},
		{"source": "coronavirus", "target": "message", "value": 4},
		{"source": "coronavirus", "target": "subject", "value": 4},
		{"source": "coronavirus", "target": "np", "value": 4},
		{"source": "coronavirus", "target": "amp", "value": 4},
		{"source": "coronavirus", "target": "ajg", "value": 4},
		{"source": "coronavirus", "target": "redd", "value": 4},
		{"source": "coronavirus", "target": "http", "value": 4},
		{"source": "coronavirus", "target": "reminde", "value": 4},
		{"source": "coronavirus", "target": "comments", "value": 4},
		{"source": "coronavirus", "target": "forbes", "value": 4},
		{"source": "coronavirus", "target": "com", "value": 4},
		{"source": "coronavirus", "target": "gallery", "value": 4},
		{"source": "coronavirus", "target": "remindmebot", "value": 4},
		{"source": "coronavirus", "target": "wolframalpha", "value": 4},
		{"source": "coronavirus", "target": "gov", "value": 4},
		{"source": "smell", "target": "taste", "value": 4},
		{"source": "smell", "target": "lost", "value": 4},
		{"source": "smell", "target": "sense", "value": 4},
		{"source": "smell", "target": "ish", "value": 3},
		{"source": "smell", "target": "half", "value": 3},
		{"source": "smell", "target": "senses", "value": 3},
		{"source": "smell", "target": "pronounced", "value": 3},
		{"source": "smell", "target": "gi", "value": 3},
		{"source": "smell", "target": "loss", "value": 3},
		{"source": "smell", "target": "early", "value": 3},
		{"source": "smell", "target": "tongue", "value": 3},
		{"source": "smell", "target": "flew", "value": 3},
		{"source": "smell", "target": "feb", "value": 3},
		{"source": "smell", "target": "appetite", "value": 3},
		{"source": "smell", "target": "shivering", "value": 3},
		{"source": "smell", "target": "recall", "value": 3},
		{"source": "smell", "target": "old", "value": 3},
		{"source": "smell", "target": "one", "value": 3},
		{"source": "smell", "target": "yea", "value": 3},
		{"source": "smell", "target": "hou", "value": 3},
		{"source": "taste", "target": "smell", "value": 4},
		{"source": "taste", "target": "sense", "value": 4},
		{"source": "taste", "target": "lost", "value": 4},
		{"source": "taste", "target": "senses", "value": 3},
		{"source": "taste", "target": "loss", "value": 3},
		{"source": "taste", "target": "half", "value": 3},
		{"source": "taste", "target": "ish", "value": 3},
		{"source": "taste", "target": "appetite", "value": 3},
		{"source": "taste", "target": "early", "value": 3},
		{"source": "taste", "target": "fou", "value": 3},
		{"source": "taste", "target": "began", "value": 3},
		{"source": "taste", "target": "flew", "value": 3},
		{"source": "taste", "target": "pronounced", "value": 3},
		{"source": "taste", "target": "airport", "value": 3},
		{"source": "taste", "target": "broke", "value": 3},
		{"source": "taste", "target": "nostril", "value": 3},
		{"source": "taste", "target": "shivering", "value": 3},
		{"source": "taste", "target": "tongue", "value": 3},
		{"source": "taste", "target": "christmas", "value": 3},
		{"source": "taste", "target": "feb", "value": 3},
		{"source": "symptoms", "target": "went", "value": 4},
		{"source": "symptoms", "target": "ive", "value": 4},
		{"source": "symptoms", "target": "since", "value": 4},
		{"source": "symptoms", "target": "got", "value": 4},
		{"source": "symptoms", "target": "afte", "value": 4},
		{"source": "symptoms", "target": "back", "value": 4},
		{"source": "symptoms", "target": "couple", "value": 4},
		{"source": "symptoms", "target": "night", "value": 4},
		{"source": "symptoms", "target": "mild", "value": 4},
		{"source": "symptoms", "target": "past", "value": 4},
		{"source": "symptoms", "target": "runny", "value": 4},
		{"source": "symptoms", "target": "day", "value": 4},
		{"source": "symptoms", "target": "coughing", "value": 4},
		{"source": "symptoms", "target": "weeks", "value": 4},
		{"source": "symptoms", "target": "headache", "value": 4},
		{"source": "symptoms", "target": "aches", "value": 4},
		{"source": "symptoms", "target": "almost", "value": 4},
		{"source": "symptoms", "target": "diarrhea", "value": 4},
		{"source": "symptoms", "target": "bad", "value": 3},
		{"source": "symptoms", "target": "friday", "value": 3},
		{"source": "negative", "target": "even", "value": 4},
		{"source": "negative", "target": "think", "value": 4},
		{"source": "negative", "target": "waiting", "value": 4},
		{"source": "negative", "target": "warrant", "value": 4},
		{"source": "negative", "target": "told", "value": 4},
		{"source": "negative", "target": "wait", "value": 4},
		{"source": "negative", "target": "yet", "value": 4},
		{"source": "negative", "target": "didnt", "value": 4},
		{"source": "negative", "target": "cant", "value": 4},
		{"source": "negative", "target": "come", "value": 4},
		{"source": "negative", "target": "urgent", "value": 4},
		{"source": "negative", "target": "hospital", "value": 4},
		{"source": "negative", "target": "exposed", "value": 4},
		{"source": "negative", "target": "husband", "value": 4},
		{"source": "negative", "target": "winte", "value": 4},
		{"source": "negative", "target": "denied", "value": 3},
		{"source": "negative", "target": "without", "value": 3},
		{"source": "negative", "target": "work", "value": 3},
		{"source": "negative", "target": "whilst", "value": 3},
		{"source": "negative", "target": "honestly", "value": 3}
	]
}
