var graph_anonymous = {
	"nodes": [
		{"id": "covid", "group": 1},
		{"id": "january", "group": 1},
		{"id": "article", "group": 1},
		{"id": "email", "group": 1},
		{"id": "articles", "group": 1},
		{"id": "add", "group": 1},
		{"id": "news", "group": 1},
		{"id": "frozen", "group": 1},
		{"id": "th", "group": 1},
		{"id": "questions", "group": 1},
		{"id": "st", "group": 1},
		{"id": "videos", "group": 1},
		{"id": "facebook", "group": 1},
		{"id": "normalcy", "group": 1},
		{"id": "source", "group": 1},
		{"id": "google", "group": 1},
		{"id": "opinion", "group": 1},
		{"id": "ca", "group": 1},
		{"id": "top", "group": 1},
		{"id": "jobs", "group": 1},
		{"id": "info", "group": 1},
		{"id": "positive", "group": 2},
		{"id": "yes", "group": 2},
		{"id": "also", "group": 2},
		{"id": "real", "group": 2},
		{"id": "kind", "group": 2},
		{"id": "fea", "group": 2},
		{"id": "likely", "group": 2},
		{"id": "believe", "group": 2},
		{"id": "long", "group": 2},
		{"id": "change", "group": 2},
		{"id": "testing", "group": 2},
		{"id": "cannot", "group": 2},
		{"id": "plan", "group": 2},
		{"id": "making", "group": 2},
		{"id": "stop", "group": 2},
		{"id": "gets", "group": 2},
		{"id": "made", "group": 2},
		{"id": "case", "group": 2},
		{"id": "government", "group": 2},
		{"id": "thats", "group": 2},
		{"id": "medical", "group": 2},
		{"id": "coronavirus", "group": 3},
		{"id": "gov", "group": 3},
		{"id": "covanonymous", "group": 3},
		{"id": "china_flu", "group": 3},
		{"id": "watch", "group": 3},
		{"id": "en", "group": 3},
		{"id": "org", "group": 3},
		{"id": "nih", "group": 3},
		{"id": "wiki", "group": 3},
		{"id": "utc", "group": 3},
		{"id": "html", "group": 3},
		{"id": "ddc", "group": 3},
		{"id": "pdf", "group": 3},
		{"id": "io", "group": 3},
		{"id": "youtube", "group": 3},
		{"id": "http", "group": 3},
		{"id": "fd", "group": 3},
		{"id": "reminders", "group": 3},
		{"id": "fad", "group": 3},
		{"id": "link", "group": 3},
		{"id": "wikipedia", "group": 3},
		{"id": "smell", "group": 4},
		{"id": "issues", "group": 4},
		{"id": "definitely", "group": 4},
		{"id": "delivery", "group": 4},
		{"id": "worst", "group": 4},
		{"id": "numbers", "group": 4},
		{"id": "look", "group": 4},
		{"id": "agree", "group": 4},
		{"id": "yesterday", "group": 4},
		{"id": "give", "group": 4},
		{"id": "test", "group": 4},
		{"id": "theyre", "group": 4},
		{"id": "night", "group": 4},
		{"id": "without", "group": 4},
		{"id": "stuck", "group": 4},
		{"id": "husband", "group": 4},
		{"id": "next", "group": 4},
		{"id": "place", "group": 4},
		{"id": "self", "group": 4},
		{"id": "taste", "group": 5},
		{"id": "theres", "group": 5},
		{"id": "running", "group": 5},
		{"id": "oh", "group": 5},
		{"id": "hell", "group": 5},
		{"id": "please", "group": 5},
		{"id": "infection", "group": 5},
		{"id": "less", "group": 5},
		{"id": "stuff", "group": 5},
		{"id": "open", "group": 5},
		{"id": "anyway", "group": 5},
		{"id": "gives", "group": 5},
		{"id": "looks", "group": 5},
		{"id": "die", "group": 5},
		{"id": "spent", "group": 5},
		{"id": "body", "group": 5},
		{"id": "pay", "group": 5},
		{"id": "symptoms", "group": 6},
		{"id": "cough", "group": 6},
		{"id": "feve", "group": 6},
		{"id": "mild", "group": 6},
		{"id": "past", "group": 6},
		{"id": "went", "group": 6},
		{"id": "didnt", "group": 6},
		{"id": "heard", "group": 6},
		{"id": "completely", "group": 6},
		{"id": "coughing", "group": 6},
		{"id": "throat", "group": 6},
		{"id": "hospital", "group": 6},
		{"id": "helps", "group": 6},
		{"id": "call", "group": 6},
		{"id": "panic", "group": 6},
		{"id": "havent", "group": 6},
		{"id": "anyone", "group": 6},
		{"id": "negative", "group": 7},
		{"id": "live", "group": 7},
		{"id": "someone", "group": 7},
		{"id": "must", "group": 7},
		{"id": "every", "group": 7},
		{"id": "almost", "group": 7},
		{"id": "late", "group": 7},
		{"id": "ill", "group": 7},
		{"id": "school", "group": 7},
		{"id": "buy", "group": 7},
		{"id": "store", "group": 7},
		{"id": "seeing", "group": 7},
		{"id": "today", "group": 7},
		{"id": "years", "group": 7},
		{"id": "especially", "group": 7},
		{"id": "yea", "group": 7},
		{"id": "single", "group": 7}
	],
	"links": [
		{"source": "covid", "target": "january", "value": 4},
		{"source": "covid", "target": "article", "value": 4},
		{"source": "covid", "target": "email", "value": 4},
		{"source": "covid", "target": "articles", "value": 4},
		{"source": "covid", "target": "add", "value": 4},
		{"source": "covid", "target": "news", "value": 4},
		{"source": "covid", "target": "frozen", "value": 4},
		{"source": "covid", "target": "th", "value": 4},
		{"source": "covid", "target": "questions", "value": 4},
		{"source": "covid", "target": "st", "value": 4},
		{"source": "covid", "target": "videos", "value": 4},
		{"source": "covid", "target": "facebook", "value": 4},
		{"source": "covid", "target": "normalcy", "value": 4},
		{"source": "covid", "target": "source", "value": 4},
		{"source": "covid", "target": "google", "value": 4},
		{"source": "covid", "target": "opinion", "value": 4},
		{"source": "covid", "target": "ca", "value": 4},
		{"source": "covid", "target": "top", "value": 4},
		{"source": "covid", "target": "jobs", "value": 4},
		{"source": "covid", "target": "info", "value": 4},
		{"source": "positive", "target": "yes", "value": 4},
		{"source": "positive", "target": "also", "value": 4},
		{"source": "positive", "target": "real", "value": 4},
		{"source": "positive", "target": "kind", "value": 4},
		{"source": "positive", "target": "fea", "value": 4},
		{"source": "positive", "target": "likely", "value": 4},
		{"source": "positive", "target": "believe", "value": 4},
		{"source": "positive", "target": "long", "value": 4},
		{"source": "positive", "target": "change", "value": 4},
		{"source": "positive", "target": "testing", "value": 4},
		{"source": "positive", "target": "cannot", "value": 4},
		{"source": "positive", "target": "plan", "value": 4},
		{"source": "positive", "target": "making", "value": 4},
		{"source": "positive", "target": "stop", "value": 4},
		{"source": "positive", "target": "gets", "value": 4},
		{"source": "positive", "target": "made", "value": 4},
		{"source": "positive", "target": "case", "value": 4},
		{"source": "positive", "target": "government", "value": 4},
		{"source": "positive", "target": "thats", "value": 4},
		{"source": "positive", "target": "medical", "value": 4},
		{"source": "coronavirus", "target": "gov", "value": 4},
		{"source": "coronavirus", "target": "covanonymous", "value": 4},
		{"source": "coronavirus", "target": "china_flu", "value": 4},
		{"source": "coronavirus", "target": "watch", "value": 4},
		{"source": "coronavirus", "target": "en", "value": 4},
		{"source": "coronavirus", "target": "org", "value": 4},
		{"source": "coronavirus", "target": "nih", "value": 4},
		{"source": "coronavirus", "target": "wiki", "value": 4},
		{"source": "coronavirus", "target": "utc", "value": 4},
		{"source": "coronavirus", "target": "html", "value": 4},
		{"source": "coronavirus", "target": "ddc", "value": 4},
		{"source": "coronavirus", "target": "pdf", "value": 4},
		{"source": "coronavirus", "target": "io", "value": 4},
		{"source": "coronavirus", "target": "youtube", "value": 4},
		{"source": "coronavirus", "target": "http", "value": 4},
		{"source": "coronavirus", "target": "fd", "value": 4},
		{"source": "coronavirus", "target": "reminders", "value": 4},
		{"source": "coronavirus", "target": "fad", "value": 4},
		{"source": "coronavirus", "target": "link", "value": 4},
		{"source": "coronavirus", "target": "wikipedia", "value": 4},
		{"source": "smell", "target": "issues", "value": 4},
		{"source": "smell", "target": "definitely", "value": 4},
		{"source": "smell", "target": "delivery", "value": 4},
		{"source": "smell", "target": "worst", "value": 4},
		{"source": "smell", "target": "numbers", "value": 4},
		{"source": "smell", "target": "look", "value": 4},
		{"source": "smell", "target": "agree", "value": 4},
		{"source": "smell", "target": "yesterday", "value": 4},
		{"source": "smell", "target": "give", "value": 4},
		{"source": "smell", "target": "test", "value": 4},
		{"source": "smell", "target": "theyre", "value": 4},
		{"source": "smell", "target": "night", "value": 4},
		{"source": "smell", "target": "without", "value": 4},
		{"source": "smell", "target": "stuck", "value": 4},
		{"source": "smell", "target": "husband", "value": 4},
		{"source": "smell", "target": "next", "value": 4},
		{"source": "smell", "target": "place", "value": 4},
		{"source": "smell", "target": "yes", "value": 4},
		{"source": "smell", "target": "real", "value": 4},
		{"source": "smell", "target": "self", "value": 4},
		{"source": "taste", "target": "theres", "value": 4},
		{"source": "taste", "target": "running", "value": 4},
		{"source": "taste", "target": "oh", "value": 4},
		{"source": "taste", "target": "hell", "value": 4},
		{"source": "taste", "target": "please", "value": 4},
		{"source": "taste", "target": "infection", "value": 4},
		{"source": "taste", "target": "less", "value": 4},
		{"source": "taste", "target": "stuff", "value": 4},
		{"source": "taste", "target": "also", "value": 4},
		{"source": "taste", "target": "fea", "value": 4},
		{"source": "taste", "target": "open", "value": 4},
		{"source": "taste", "target": "anyway", "value": 4},
		{"source": "taste", "target": "gives", "value": 4},
		{"source": "taste", "target": "looks", "value": 4},
		{"source": "taste", "target": "die", "value": 4},
		{"source": "taste", "target": "spent", "value": 4},
		{"source": "taste", "target": "body", "value": 4},
		{"source": "taste", "target": "yes", "value": 4},
		{"source": "taste", "target": "look", "value": 4},
		{"source": "taste", "target": "pay", "value": 4},
		{"source": "symptoms", "target": "cough", "value": 4},
		{"source": "symptoms", "target": "feve", "value": 4},
		{"source": "symptoms", "target": "mild", "value": 4},
		{"source": "symptoms", "target": "case", "value": 4},
		{"source": "symptoms", "target": "test", "value": 4},
		{"source": "symptoms", "target": "past", "value": 4},
		{"source": "symptoms", "target": "went", "value": 4},
		{"source": "symptoms", "target": "didnt", "value": 4},
		{"source": "symptoms", "target": "heard", "value": 4},
		{"source": "symptoms", "target": "completely", "value": 4},
		{"source": "symptoms", "target": "coughing", "value": 4},
		{"source": "symptoms", "target": "throat", "value": 4},
		{"source": "symptoms", "target": "hospital", "value": 4},
		{"source": "symptoms", "target": "helps", "value": 4},
		{"source": "symptoms", "target": "without", "value": 4},
		{"source": "symptoms", "target": "self", "value": 4},
		{"source": "symptoms", "target": "call", "value": 4},
		{"source": "symptoms", "target": "panic", "value": 4},
		{"source": "symptoms", "target": "havent", "value": 4},
		{"source": "symptoms", "target": "anyone", "value": 4},
		{"source": "negative", "target": "live", "value": 4},
		{"source": "negative", "target": "someone", "value": 4},
		{"source": "negative", "target": "must", "value": 4},
		{"source": "negative", "target": "every", "value": 4},
		{"source": "negative", "target": "almost", "value": 4},
		{"source": "negative", "target": "case", "value": 4},
		{"source": "negative", "target": "late", "value": 4},
		{"source": "negative", "target": "ill", "value": 4},
		{"source": "negative", "target": "school", "value": 4},
		{"source": "negative", "target": "buy", "value": 4},
		{"source": "negative", "target": "store", "value": 4},
		{"source": "negative", "target": "seeing", "value": 4},
		{"source": "negative", "target": "didnt", "value": 4},
		{"source": "negative", "target": "today", "value": 4},
		{"source": "negative", "target": "yes", "value": 4},
		{"source": "negative", "target": "years", "value": 4},
		{"source": "negative", "target": "went", "value": 4},
		{"source": "negative", "target": "especially", "value": 4},
		{"source": "negative", "target": "yea", "value": 4},
		{"source": "negative", "target": "single", "value": 4}
	]
}
