var graph_positive = {
	"nodes": [
		{"id": "covid", "group": 1},
		{"id": "coronavirus", "group": 1},
		{"id": "ebv", "group": 1},
		{"id": "corona", "group": 1},
		{"id": "influenza", "group": 1},
		{"id": "virus", "group": 1},
		{"id": "sars", "group": 1},
		{"id": "suspected", "group": 1},
		{"id": "known", "group": 1},
		{"id": "diagnosed", "group": 1},
		{"id": "treated", "group": 1},
		{"id": "confirmed", "group": 1},
		{"id": "suspect", "group": 1},
		{"id": "mono", "group": 1},
		{"id": "hospitalized", "group": 1},
		{"id": "acute", "group": 1},
		{"id": "reinfection", "group": 1},
		{"id": "symptomatic", "group": 1},
		{"id": "lyme", "group": 1},
		{"id": "mers", "group": 1},
		{"id": "reported", "group": 1},
		{"id": "positive", "group": 2},
		{"id": "negative", "group": 2},
		{"id": "postive", "group": 2},
		{"id": "positives", "group": 2},
		{"id": "exposed", "group": 2},
		{"id": "neg", "group": 2},
		{"id": "officially", "group": 2},
		{"id": "asymptomatic", "group": 2},
		{"id": "exposure", "group": 2},
		{"id": "negatives", "group": 2},
		{"id": "quarantined", "group": 2},
		{"id": "received", "group": 2},
		{"id": "coworke", "group": 2},
		{"id": "awaiting", "group": 2},
		{"id": "denied", "group": 2},
		{"id": "waiting", "group": 2},
		{"id": "pc", "group": 2},
		{"id": "pos", "group": 2},
		{"id": "got", "group": 2},
		{"id": "eligible", "group": 2},
		{"id": "html", "group": 3},
		{"id": "ncov", "group": 3},
		{"id": "gov", "group": 3},
		{"id": "theconversation", "group": 3},
		{"id": "cov", "group": 3},
		{"id": "italy", "group": 3},
		{"id": "businessinside", "group": 3},
		{"id": "loico", "group": 3},
		{"id": "sections", "group": 3},
		{"id": "current", "group": 3},
		{"id": "potential", "group": 3},
		{"id": "korea", "group": 3},
		{"id": "wuhan", "group": 3},
		{"id": "herd", "group": 3},
		{"id": "hiv", "group": 3},
		{"id": "emerging", "group": 3},
		{"id": "western", "group": 3},
		{"id": "smell", "group": 4},
		{"id": "senses", "group": 4},
		{"id": "taste", "group": 4},
		{"id": "buds", "group": 4},
		{"id": "metallic", "group": 4},
		{"id": "appetite", "group": 4},
		{"id": "partial", "group": 4},
		{"id": "muted", "group": 4},
		{"id": "whiffs", "group": 4},
		{"id": "saltiness", "group": 4},
		{"id": "whiff", "group": 4},
		{"id": "altered", "group": 4},
		{"id": "smelling", "group": 4},
		{"id": "scent", "group": 4},
		{"id": "salty", "group": 4},
		{"id": "smells", "group": 4},
		{"id": "oddest", "group": 4},
		{"id": "burgers", "group": 4},
		{"id": "hai", "group": 4},
		{"id": "tasting", "group": 4},
		{"id": "gradual", "group": 4},
		{"id": "faintly", "group": 5},
		{"id": "burnt", "group": 5},
		{"id": "smelled", "group": 5},
		{"id": "disappeared", "group": 5},
		{"id": "perfume", "group": 5},
		{"id": "phantom", "group": 5},
		{"id": "rancid", "group": 5},
		{"id": "tasted", "group": 5},
		{"id": "symptoms", "group": 6},
		{"id": "symptom", "group": 6},
		{"id": "fever", "group": 6},
		{"id": "illness", "group": 6},
		{"id": "sickness", "group": 6},
		{"id": "signs", "group": 6},
		{"id": "headaches", "group": 6},
		{"id": "sob", "group": 6},
		{"id": "issues", "group": 6},
		{"id": "symtpoms", "group": 6},
		{"id": "diarrhea", "group": 6},
		{"id": "feve", "group": 6},
		{"id": "headache", "group": 6},
		{"id": "fatigue", "group": 6},
		{"id": "cough", "group": 6},
		{"id": "case", "group": 6},
		{"id": "howeve", "group": 6},
		{"id": "illnesses", "group": 6},
		{"id": "bout", "group": 6},
		{"id": "dizziness", "group": 6},
		{"id": "rapid", "group": 7},
		{"id": "antibodies", "group": 7},
		{"id": "antibody", "group": 7},
		{"id": "rt", "group": 7},
		{"id": "igg", "group": 7},
		{"id": "scheduled", "group": 7},
		{"id": "strep", "group": 7},
		{"id": "cleared", "group": 7},
		{"id": "results", "group": 7},
		{"id": "igm", "group": 7}
	],
	"links": [
		{"source": "covid", "target": "coronavirus", "value": 2},
		{"source": "covid", "target": "ebv", "value": 2},
		{"source": "covid", "target": "corona", "value": 2},
		{"source": "covid", "target": "influenza", "value": 2},
		{"source": "covid", "target": "virus", "value": 2},
		{"source": "covid", "target": "sars", "value": 2},
		{"source": "covid", "target": "suspected", "value": 2},
		{"source": "covid", "target": "known", "value": 2},
		{"source": "covid", "target": "diagnosed", "value": 2},
		{"source": "covid", "target": "treated", "value": 2},
		{"source": "covid", "target": "confirmed", "value": 2},
		{"source": "covid", "target": "suspect", "value": 2},
		{"source": "covid", "target": "mono", "value": 2},
		{"source": "covid", "target": "hospitalized", "value": 2},
		{"source": "covid", "target": "acute", "value": 2},
		{"source": "covid", "target": "reinfection", "value": 2},
		{"source": "covid", "target": "symptomatic", "value": 2},
		{"source": "covid", "target": "lyme", "value": 2},
		{"source": "covid", "target": "mers", "value": 2},
		{"source": "covid", "target": "reported", "value": 2},
		{"source": "positive", "target": "negative", "value": 3},
		{"source": "positive", "target": "postive", "value": 3},
		{"source": "positive", "target": "symptomatic", "value": 2},
		{"source": "positive", "target": "positives", "value": 2},
		{"source": "positive", "target": "exposed", "value": 2},
		{"source": "positive", "target": "neg", "value": 2},
		{"source": "positive", "target": "officially", "value": 2},
		{"source": "positive", "target": "asymptomatic", "value": 2},
		{"source": "positive", "target": "exposure", "value": 2},
		{"source": "positive", "target": "negatives", "value": 2},
		{"source": "positive", "target": "quarantined", "value": 2},
		{"source": "positive", "target": "received", "value": 2},
		{"source": "positive", "target": "coworke", "value": 2},
		{"source": "positive", "target": "awaiting", "value": 2},
		{"source": "positive", "target": "denied", "value": 2},
		{"source": "positive", "target": "waiting", "value": 2},
		{"source": "positive", "target": "pc", "value": 2},
		{"source": "positive", "target": "pos", "value": 2},
		{"source": "positive", "target": "got", "value": 2},
		{"source": "positive", "target": "eligible", "value": 2},
		{"source": "coronavirus", "target": "html", "value": 3},
		{"source": "coronavirus", "target": "ncov", "value": 3},
		{"source": "coronavirus", "target": "sars", "value": 3},
		{"source": "coronavirus", "target": "gov", "value": 3},
		{"source": "coronavirus", "target": "theconversation", "value": 3},
		{"source": "coronavirus", "target": "cov", "value": 3},
		{"source": "coronavirus", "target": "italy", "value": 3},
		{"source": "coronavirus", "target": "mers", "value": 3},
		{"source": "coronavirus", "target": "businessinside", "value": 3},
		{"source": "coronavirus", "target": "loico", "value": 3},
		{"source": "coronavirus", "target": "sections", "value": 3},
		{"source": "coronavirus", "target": "current", "value": 3},
		{"source": "coronavirus", "target": "potential", "value": 3},
		{"source": "coronavirus", "target": "korea", "value": 3},
		{"source": "coronavirus", "target": "wuhan", "value": 3},
		{"source": "coronavirus", "target": "reported", "value": 3},
		{"source": "coronavirus", "target": "herd", "value": 3},
		{"source": "coronavirus", "target": "hiv", "value": 3},
		{"source": "coronavirus", "target": "emerging", "value": 3},
		{"source": "coronavirus", "target": "western", "value": 3},
		{"source": "smell", "target": "senses", "value": 3},
		{"source": "smell", "target": "taste", "value": 3},
		{"source": "smell", "target": "buds", "value": 3},
		{"source": "smell", "target": "metallic", "value": 3},
		{"source": "smell", "target": "appetite", "value": 3},
		{"source": "smell", "target": "partial", "value": 3},
		{"source": "smell", "target": "muted", "value": 3},
		{"source": "smell", "target": "whiffs", "value": 2},
		{"source": "smell", "target": "saltiness", "value": 2},
		{"source": "smell", "target": "whiff", "value": 2},
		{"source": "smell", "target": "altered", "value": 2},
		{"source": "smell", "target": "smelling", "value": 2},
		{"source": "smell", "target": "scent", "value": 2},
		{"source": "smell", "target": "salty", "value": 2},
		{"source": "smell", "target": "smells", "value": 2},
		{"source": "smell", "target": "oddest", "value": 2},
		{"source": "smell", "target": "burgers", "value": 2},
		{"source": "smell", "target": "hai", "value": 2},
		{"source": "smell", "target": "tasting", "value": 2},
		{"source": "smell", "target": "gradual", "value": 2},
		{"source": "taste", "target": "senses", "value": 3},
		{"source": "taste", "target": "smell", "value": 3},
		{"source": "taste", "target": "appetite", "value": 3},
		{"source": "taste", "target": "whiff", "value": 3},
		{"source": "taste", "target": "smells", "value": 3},
		{"source": "taste", "target": "metallic", "value": 3},
		{"source": "taste", "target": "smelling", "value": 3},
		{"source": "taste", "target": "altered", "value": 3},
		{"source": "taste", "target": "faintly", "value": 3},
		{"source": "taste", "target": "tasting", "value": 3},
		{"source": "taste", "target": "scent", "value": 3},
		{"source": "taste", "target": "burnt", "value": 3},
		{"source": "taste", "target": "whiffs", "value": 3},
		{"source": "taste", "target": "smelled", "value": 3},
		{"source": "taste", "target": "disappeared", "value": 3},
		{"source": "taste", "target": "salty", "value": 3},
		{"source": "taste", "target": "perfume", "value": 2},
		{"source": "taste", "target": "phantom", "value": 2},
		{"source": "taste", "target": "rancid", "value": 2},
		{"source": "taste", "target": "tasted", "value": 2},
		{"source": "symptoms", "target": "symptom", "value": 3},
		{"source": "symptoms", "target": "fever", "value": 3},
		{"source": "symptoms", "target": "illness", "value": 2},
		{"source": "symptoms", "target": "sickness", "value": 2},
		{"source": "symptoms", "target": "signs", "value": 2},
		{"source": "symptoms", "target": "headaches", "value": 2},
		{"source": "symptoms", "target": "sob", "value": 2},
		{"source": "symptoms", "target": "issues", "value": 2},
		{"source": "symptoms", "target": "symtpoms", "value": 2},
		{"source": "symptoms", "target": "diarrhea", "value": 2},
		{"source": "symptoms", "target": "feve", "value": 2},
		{"source": "symptoms", "target": "headache", "value": 2},
		{"source": "symptoms", "target": "fatigue", "value": 2},
		{"source": "symptoms", "target": "cough", "value": 2},
		{"source": "symptoms", "target": "case", "value": 2},
		{"source": "symptoms", "target": "howeve", "value": 2},
		{"source": "symptoms", "target": "illnesses", "value": 2},
		{"source": "symptoms", "target": "bout", "value": 2},
		{"source": "symptoms", "target": "exposure", "value": 2},
		{"source": "symptoms", "target": "dizziness", "value": 2},
		{"source": "negative", "target": "positive", "value": 3},
		{"source": "negative", "target": "negatives", "value": 3},
		{"source": "negative", "target": "neg", "value": 3},
		{"source": "negative", "target": "positives", "value": 3},
		{"source": "negative", "target": "pc", "value": 2},
		{"source": "negative", "target": "rapid", "value": 2},
		{"source": "negative", "target": "postive", "value": 2},
		{"source": "negative", "target": "waiting", "value": 2},
		{"source": "negative", "target": "antibodies", "value": 2},
		{"source": "negative", "target": "antibody", "value": 2},
		{"source": "negative", "target": "rt", "value": 2},
		{"source": "negative", "target": "igg", "value": 2},
		{"source": "negative", "target": "scheduled", "value": 2},
		{"source": "negative", "target": "awaiting", "value": 2},
		{"source": "negative", "target": "strep", "value": 2},
		{"source": "negative", "target": "cleared", "value": 2},
		{"source": "negative", "target": "results", "value": 2},
		{"source": "negative", "target": "received", "value": 2},
		{"source": "negative", "target": "igm", "value": 2},
		{"source": "negative", "target": "symptomatic", "value": 2}
	]
}
