var graph_support = {
	"nodes": [
		{"id": "covid", "group": 1},
		{"id": "covid19", "group": 1},
		{"id": "virus", "group": 1},
		{"id": "corona", "group": 1},
		{"id": "hospitalized", "group": 1},
		{"id": "coronavirus", "group": 1},
		{"id": "disease", "group": 1},
		{"id": "result", "group": 1},
		{"id": "tested", "group": 1},
		{"id": "serious", "group": 1},
		{"id": "severe", "group": 1},
		{"id": "mild", "group": 1},
		{"id": "cance", "group": 1},
		{"id": "sick", "group": 1},
		{"id": "asymptomatic", "group": 1},
		{"id": "complications", "group": 1},
		{"id": "icu", "group": 1},
		{"id": "symptomatic", "group": 1},
		{"id": "pneumonia", "group": 1},
		{"id": "caught", "group": 1},
		{"id": "illness", "group": 1},
		{"id": "positive", "group": 2},
		{"id": "negative", "group": 2},
		{"id": "neg", "group": 2},
		{"id": "results", "group": 2},
		{"id": "positives", "group": 2},
		{"id": "negatives", "group": 2},
		{"id": "confirm", "group": 2},
		{"id": "antibody", "group": 2},
		{"id": "active", "group": 2},
		{"id": "confirmed", "group": 2},
		{"id": "rapid", "group": 2},
		{"id": "kits", "group": 2},
		{"id": "coworke", "group": 2},
		{"id": "test", "group": 2},
		{"id": "quarantined", "group": 2},
		{"id": "awaiting", "group": 2},
		{"id": "pc", "group": 2},
		{"id": "contracted", "group": 2},
		{"id": "hiv", "group": 3},
		{"id": "ebola", "group": 3},
		{"id": "reports", "group": 3},
		{"id": "sarscov2", "group": 3},
		{"id": "strains", "group": 3},
		{"id": "sars", "group": 3},
		{"id": "reinfection", "group": 3},
		{"id": "measles", "group": 3},
		{"id": "coronaviruses", "group": 3},
		{"id": "mers", "group": 3},
		{"id": "diseases", "group": 3},
		{"id": "influenza", "group": 3},
		{"id": "h1n1", "group": 3},
		{"id": "postinfection", "group": 3},
		{"id": "mutation", "group": 3},
		{"id": "viruses", "group": 3},
		{"id": "mutations", "group": 3},
		{"id": "smell", "group": 4},
		{"id": "taste", "group": 4},
		{"id": "smelltaste", "group": 4},
		{"id": "tastesmell", "group": 4},
		{"id": "throat", "group": 4},
		{"id": "sore", "group": 4},
		{"id": "tasted", "group": 4},
		{"id": "headaches", "group": 4},
		{"id": "appetite", "group": 4},
		{"id": "smelling", "group": 4},
		{"id": "throats", "group": 4},
		{"id": "headache", "group": 4},
		{"id": "chest", "group": 4},
		{"id": "tickle", "group": 4},
		{"id": "tightness", "group": 4},
		{"id": "itchy", "group": 4},
		{"id": "scratchy", "group": 4},
		{"id": "senses", "group": 4},
		{"id": "pains", "group": 4},
		{"id": "phlegm", "group": 4},
		{"id": "runny", "group": 4},
		{"id": "muscle", "group": 5},
		{"id": "aches", "group": 5},
		{"id": "ache", "group": 5},
		{"id": "symptoms", "group": 6},
		{"id": "symptom", "group": 6},
		{"id": "feve", "group": 6},
		{"id": "cough", "group": 6},
		{"id": "contagious", "group": 6},
		{"id": "signs", "group": 6},
		{"id": "recovered", "group": 6},
		{"id": "asthma", "group": 6},
		{"id": "diagnosed", "group": 6},
		{"id": "colds", "group": 6},
		{"id": "tests", "group": 6},
		{"id": "incubation", "group": 6},
		{"id": "antibodies", "group": 6},
		{"id": "false", "group": 7},
		{"id": "pixel", "group": 7},
		{"id": "igm", "group": 7},
		{"id": "antigen", "group": 7},
		{"id": "waters", "group": 7},
		{"id": "strep", "group": 7},
		{"id": "falsenegative", "group": 7}
	],
	"links": [
		{"source": "covid", "target": "covid19", "value": 3},
		{"source": "covid", "target": "virus", "value": 3},
		{"source": "covid", "target": "corona", "value": 2},
		{"source": "covid", "target": "hospitalized", "value": 2},
		{"source": "covid", "target": "coronavirus", "value": 2},
		{"source": "covid", "target": "disease", "value": 2},
		{"source": "covid", "target": "result", "value": 2},
		{"source": "covid", "target": "tested", "value": 2},
		{"source": "covid", "target": "serious", "value": 2},
		{"source": "covid", "target": "severe", "value": 2},
		{"source": "covid", "target": "mild", "value": 2},
		{"source": "covid", "target": "cance", "value": 2},
		{"source": "covid", "target": "sick", "value": 2},
		{"source": "covid", "target": "asymptomatic", "value": 2},
		{"source": "covid", "target": "complications", "value": 2},
		{"source": "covid", "target": "icu", "value": 2},
		{"source": "covid", "target": "symptomatic", "value": 2},
		{"source": "covid", "target": "pneumonia", "value": 2},
		{"source": "covid", "target": "caught", "value": 2},
		{"source": "covid", "target": "illness", "value": 2},
		{"source": "positive", "target": "negative", "value": 4},
		{"source": "positive", "target": "neg", "value": 2},
		{"source": "positive", "target": "results", "value": 2},
		{"source": "positive", "target": "positives", "value": 2},
		{"source": "positive", "target": "negatives", "value": 2},
		{"source": "positive", "target": "confirm", "value": 2},
		{"source": "positive", "target": "antibody", "value": 2},
		{"source": "positive", "target": "active", "value": 2},
		{"source": "positive", "target": "confirmed", "value": 2},
		{"source": "positive", "target": "asymptomatic", "value": 2},
		{"source": "positive", "target": "rapid", "value": 2},
		{"source": "positive", "target": "kits", "value": 2},
		{"source": "positive", "target": "result", "value": 2},
		{"source": "positive", "target": "coworke", "value": 2},
		{"source": "positive", "target": "test", "value": 2},
		{"source": "positive", "target": "quarantined", "value": 2},
		{"source": "positive", "target": "awaiting", "value": 2},
		{"source": "positive", "target": "pc", "value": 2},
		{"source": "positive", "target": "symptomatic", "value": 2},
		{"source": "positive", "target": "contracted", "value": 2},
		{"source": "coronavirus", "target": "covid19", "value": 3},
		{"source": "coronavirus", "target": "hiv", "value": 3},
		{"source": "coronavirus", "target": "ebola", "value": 3},
		{"source": "coronavirus", "target": "reports", "value": 3},
		{"source": "coronavirus", "target": "sarscov2", "value": 3},
		{"source": "coronavirus", "target": "strains", "value": 3},
		{"source": "coronavirus", "target": "sars", "value": 3},
		{"source": "coronavirus", "target": "reinfection", "value": 3},
		{"source": "coronavirus", "target": "measles", "value": 3},
		{"source": "coronavirus", "target": "coronaviruses", "value": 3},
		{"source": "coronavirus", "target": "disease", "value": 3},
		{"source": "coronavirus", "target": "mers", "value": 3},
		{"source": "coronavirus", "target": "diseases", "value": 3},
		{"source": "coronavirus", "target": "influenza", "value": 3},
		{"source": "coronavirus", "target": "h1n1", "value": 3},
		{"source": "coronavirus", "target": "postinfection", "value": 3},
		{"source": "coronavirus", "target": "mutation", "value": 3},
		{"source": "coronavirus", "target": "viruses", "value": 3},
		{"source": "coronavirus", "target": "virus", "value": 3},
		{"source": "coronavirus", "target": "mutations", "value": 3},
		{"source": "smell", "target": "taste", "value": 4},
		{"source": "smell", "target": "smelltaste", "value": 4},
		{"source": "smell", "target": "tastesmell", "value": 3},
		{"source": "smell", "target": "throat", "value": 3},
		{"source": "smell", "target": "sore", "value": 3},
		{"source": "smell", "target": "tasted", "value": 3},
		{"source": "smell", "target": "headaches", "value": 3},
		{"source": "smell", "target": "appetite", "value": 3},
		{"source": "smell", "target": "smelling", "value": 3},
		{"source": "smell", "target": "throats", "value": 3},
		{"source": "smell", "target": "headache", "value": 3},
		{"source": "smell", "target": "chest", "value": 3},
		{"source": "smell", "target": "tickle", "value": 3},
		{"source": "smell", "target": "tightness", "value": 3},
		{"source": "smell", "target": "itchy", "value": 3},
		{"source": "smell", "target": "scratchy", "value": 3},
		{"source": "smell", "target": "senses", "value": 3},
		{"source": "smell", "target": "pains", "value": 3},
		{"source": "smell", "target": "phlegm", "value": 3},
		{"source": "smell", "target": "runny", "value": 3},
		{"source": "taste", "target": "smell", "value": 4},
		{"source": "taste", "target": "smelltaste", "value": 4},
		{"source": "taste", "target": "tastesmell", "value": 3},
		{"source": "taste", "target": "senses", "value": 3},
		{"source": "taste", "target": "throat", "value": 3},
		{"source": "taste", "target": "appetite", "value": 3},
		{"source": "taste", "target": "sore", "value": 3},
		{"source": "taste", "target": "tasted", "value": 3},
		{"source": "taste", "target": "headaches", "value": 3},
		{"source": "taste", "target": "headache", "value": 3},
		{"source": "taste", "target": "smelling", "value": 3},
		{"source": "taste", "target": "throats", "value": 3},
		{"source": "taste", "target": "chest", "value": 3},
		{"source": "taste", "target": "pains", "value": 3},
		{"source": "taste", "target": "tightness", "value": 3},
		{"source": "taste", "target": "scratchy", "value": 3},
		{"source": "taste", "target": "muscle", "value": 3},
		{"source": "taste", "target": "aches", "value": 3},
		{"source": "taste", "target": "tickle", "value": 3},
		{"source": "taste", "target": "ache", "value": 3},
		{"source": "symptoms", "target": "symptom", "value": 3},
		{"source": "symptoms", "target": "feve", "value": 3},
		{"source": "symptoms", "target": "cough", "value": 3},
		{"source": "symptoms", "target": "symptomatic", "value": 3},
		{"source": "symptoms", "target": "asymptomatic", "value": 2},
		{"source": "symptoms", "target": "pneumonia", "value": 2},
		{"source": "symptoms", "target": "contagious", "value": 2},
		{"source": "symptoms", "target": "signs", "value": 2},
		{"source": "symptoms", "target": "recovered", "value": 2},
		{"source": "symptoms", "target": "asthma", "value": 2},
		{"source": "symptoms", "target": "mild", "value": 2},
		{"source": "symptoms", "target": "complications", "value": 2},
		{"source": "symptoms", "target": "illness", "value": 2},
		{"source": "symptoms", "target": "diagnosed", "value": 2},
		{"source": "symptoms", "target": "test", "value": 2},
		{"source": "symptoms", "target": "colds", "value": 2},
		{"source": "symptoms", "target": "tests", "value": 2},
		{"source": "symptoms", "target": "headache", "value": 2},
		{"source": "symptoms", "target": "incubation", "value": 2},
		{"source": "symptoms", "target": "antibodies", "value": 2},
		{"source": "negative", "target": "positive", "value": 4},
		{"source": "negative", "target": "negatives", "value": 3},
		{"source": "negative", "target": "results", "value": 3},
		{"source": "negative", "target": "neg", "value": 3},
		{"source": "negative", "target": "positives", "value": 3},
		{"source": "negative", "target": "antibody", "value": 3},
		{"source": "negative", "target": "false", "value": 3},
		{"source": "negative", "target": "rapid", "value": 3},
		{"source": "negative", "target": "confirm", "value": 2},
		{"source": "negative", "target": "test", "value": 2},
		{"source": "negative", "target": "result", "value": 2},
		{"source": "negative", "target": "awaiting", "value": 2},
		{"source": "negative", "target": "pixel", "value": 2},
		{"source": "negative", "target": "igm", "value": 2},
		{"source": "negative", "target": "antigen", "value": 2},
		{"source": "negative", "target": "kits", "value": 2},
		{"source": "negative", "target": "waters", "value": 2},
		{"source": "negative", "target": "pc", "value": 2},
		{"source": "negative", "target": "strep", "value": 2},
		{"source": "negative", "target": "falsenegative", "value": 2}
	]
}
